@extends('layouts.app')
@section('title','Rekap Poin Siswa - NUSA')
@section('content')
    <style>.point-number{color:var(--primary-dark);font-size:24px;font-weight:900}.sanction-list{display:grid;gap:10px;margin-top:14px}.sanction-item{align-items:center;border:1px solid var(--line);border-radius:8px;display:grid;gap:12px;grid-template-columns:1fr 1fr auto;padding:12px}@media(max-width:760px){.sanction-item{grid-template-columns:1fr}}</style>
    <div class="page-header"><div><p class="eyebrow">Kesiswaan & BK</p><h1 class="page-title">Rekap Poin Siswa</h1><p class="page-subtitle">Saldo poin dihitung dari transaksi yang sudah disahkan pada setiap tahun pelajaran.</p></div><a href="{{ route('pengurangan-poin-siswa.index') }}" class="button button-primary">Pengurangan Poin</a></div>
    @if(session('berhasil'))<div class="alert">{{ session('berhasil') }}</div>@endif
    <form method="GET" class="panel panel-pad" style="margin-bottom:20px"><div class="form-grid"><div class="field"><label for="tahun">Tahun pelajaran</label><select id="tahun" name="tahun_pelajaran_id" class="select">@foreach($daftarTahunPelajaran as $tahun)<option value="{{ $tahun->id }}" @selected((string)$tahunPelajaranId===(string)$tahun->id)>{{ $tahun->nama }}{{ $tahun->aktif?' (aktif)':'' }}</option>@endforeach</select></div><div class="field"><label for="kelas">Kelas</label><select id="kelas" name="kelas_id" class="select"><option value="">Semua kelas</option>@foreach($daftarKelas as $kelas)<option value="{{ $kelas->id }}" @selected((string)$kelasId===(string)$kelas->id)>{{ $kelas->nama }}</option>@endforeach</select></div><div class="field span-2"><label for="kata">Cari siswa</label><input id="kata" name="kata_kunci" value="{{ $kataKunci }}" class="input" placeholder="Nama, NIS, atau NISN"></div></div><div class="actions" style="justify-content:flex-end;margin-top:12px"><a href="{{ route('rekap-poin-siswa.index') }}" class="button button-muted">Reset</a><button class="button button-dark">Terapkan</button></div></form>
    <section class="panel"><div class="desktop-only table-wrap"><table class="employee-table"><thead><tr><th>Siswa</th><th>Kelas</th><th>Guru Wali</th><th>Total Poin</th><th class="text-right">Aksi</th></tr></thead><tbody>@forelse($daftarSiswa as $siswa)@php $anggota=$siswa->anggotaKelas->first();$guru=$siswa->penugasanGuruWaliSiswa->first()?->guruWali;$poin=max(0,(int)$siswa->total_poin);@endphp<tr><td><p class="person-name">{{ $siswa->nama_lengkap }}</p><p class="person-meta">NISN {{ $siswa->nisn?:'-' }}</p></td><td>{{ $anggota?->kelas?->nama?:'-' }}</td><td>{{ $guru?->nama_lengkap?:'-' }}</td><td><span class="point-number">{{ $poin }}</span></td><td><a class="button button-muted button-sm" href="{{ route('laporan-pembinaan-siswa.index',['kata_kunci'=>$siswa->nisn?:$siswa->nama_lengkap]) }}">Riwayat</a></td></tr>@empty<tr><td colspan="5" class="empty-state">Belum ada siswa pada cakupan ini.</td></tr>@endforelse</tbody></table></div><div class="mobile-only mobile-list">@foreach($daftarSiswa as $siswa)<article class="mobile-card"><div class="mobile-card-head"><div><p class="person-name">{{ $siswa->nama_lengkap }}</p><p class="person-meta">{{ $siswa->anggotaKelas->first()?->kelas?->nama?:'-' }}</p></div><span class="badge badge-warning">{{ max(0,(int)$siswa->total_poin) }} poin</span></div><a class="button button-muted button-sm" style="margin-top:10px" href="{{ route('laporan-pembinaan-siswa.index',['kata_kunci'=>$siswa->nisn?:$siswa->nama_lengkap]) }}">Riwayat</a></article>@endforeach</div></section>
    @if($daftarSiswa->hasPages())<nav class="pagination-simple"><span>Halaman {{ $daftarSiswa->currentPage() }} dari {{ $daftarSiswa->lastPage() }}</span><div class="actions">@if($daftarSiswa->onFirstPage())<span class="button button-muted">Sebelumnya</span>@else<a href="{{ $daftarSiswa->previousPageUrl() }}" class="button button-muted">Sebelumnya</a>@endif @if($daftarSiswa->hasMorePages())<a href="{{ $daftarSiswa->nextPageUrl() }}" class="button button-muted">Berikutnya</a>@endif</div></nav>@endif
    @if($sanksiMenunggu->isNotEmpty())<section class="panel panel-pad" style="margin-top:22px"><h2 class="panel-title">Sanksi yang Perlu Ditindaklanjuti</h2><div class="sanction-list">@foreach($sanksiMenunggu as $sanksi)<article class="sanction-item"><div><p class="person-name">{{ $sanksi->siswa?->nama_lengkap }}</p><p class="person-meta">{{ $sanksi->poin_saat_terpicu }} poin saat terpicu</p></div><div><strong>{{ $sanksi->aturanSanksiPoin?->nama }}</strong><p class="person-meta">Ambang {{ $sanksi->aturanSanksiPoin?->batas_poin }} poin</p></div>@izin('poin_siswa.reward_kelola')<form method="POST" action="{{ route('sanksi-poin-siswa.update',$sanksi) }}">@csrf @method('PUT')<select name="status" class="select"><option value="menunggu" @selected($sanksi->status==='menunggu')>Menunggu</option><option value="diproses" @selected($sanksi->status==='diproses')>Diproses</option><option value="selesai">Selesai</option><option value="dibatalkan">Dibatalkan</option></select><input name="catatan" class="input" placeholder="Catatan" style="margin-top:6px"><button class="button button-dark button-sm" style="margin-top:6px">Simpan</button></form>@endizin</article>@endforeach</div></section>@endif
@endsection
