@extends('layouts.app')
@section('title','Rekap Poin Siswa - NUSA')
@section('content')
    <style>.point-number{color:var(--primary-dark);font-size:24px;font-weight:900}</style>
    <div class="page-header"><div><p class="eyebrow">Kesiswaan & BK</p><h1 class="page-title">Rekap Poin Siswa</h1><p class="page-subtitle">Saldo poin dihitung dari transaksi yang sudah disahkan pada setiap tahun pelajaran.</p></div><div class="actions"><a href="{{ route('sanksi-poin-siswa.index') }}" class="button button-muted">Pelaksanaan Sanksi</a>@izin('poin_siswa.reward_kelola')<a href="{{ route('pengurangan-poin-siswa.index') }}" class="button button-primary">Pengurangan Poin</a>@endizin</div></div>
    @if(session('berhasil'))<div class="alert">{{ session('berhasil') }}</div>@endif
    <form method="GET" class="panel panel-pad" style="margin-bottom:20px"><div class="form-grid"><div class="field"><label for="tahun">Tahun pelajaran</label><select id="tahun" name="tahun_pelajaran_id" class="select">@foreach($daftarTahunPelajaran as $tahun)<option value="{{ $tahun->id }}" @selected((string)$tahunPelajaranId===(string)$tahun->id)>{{ $tahun->nama }}{{ $tahun->aktif?' (aktif)':'' }}</option>@endforeach</select></div><div class="field"><label for="kelas">Kelas</label><select id="kelas" name="kelas_id" class="select"><option value="">Semua kelas</option>@foreach($daftarKelas as $kelas)<option value="{{ $kelas->id }}" @selected((string)$kelasId===(string)$kelas->id)>{{ $kelas->nama }}</option>@endforeach</select></div><div class="field span-2"><label for="kata">Cari siswa</label><input id="kata" name="kata_kunci" value="{{ $kataKunci }}" class="input" placeholder="Nama, NIS, atau NISN"></div></div><div class="actions" style="justify-content:flex-end;margin-top:12px"><a href="{{ route('rekap-poin-siswa.index') }}" class="button button-muted">Reset</a><button class="button button-dark">Terapkan</button></div></form>
    <section class="panel"><div class="desktop-only table-wrap"><table class="employee-table"><thead><tr><th>Siswa</th><th>Kelas</th><th>Guru Wali</th><th>Total Poin</th><th class="text-right">Aksi</th></tr></thead><tbody>@forelse($daftarSiswa as $siswa)@php $anggota=$siswa->anggotaKelas->first();$guru=$siswa->penugasanGuruWaliSiswa->first()?->guruWali;$poin=max(0,(int)$siswa->total_poin);@endphp<tr><td><p class="person-name">{{ $siswa->nama_lengkap }}</p><p class="person-meta">NISN {{ $siswa->nisn?:'-' }}</p></td><td>{{ $anggota?->kelas?->nama?:'-' }}</td><td>{{ $guru?->nama_lengkap?:'-' }}</td><td><span class="point-number">{{ $poin }}</span></td><td><a class="button button-muted button-sm" href="{{ route('laporan-pembinaan-siswa.index',['kata_kunci'=>$siswa->nisn?:$siswa->nama_lengkap]) }}">Riwayat</a></td></tr>@empty<tr><td colspan="5" class="empty-state">Belum ada siswa pada cakupan ini.</td></tr>@endforelse</tbody></table></div><div class="mobile-only mobile-list">@foreach($daftarSiswa as $siswa)<article class="mobile-card"><div class="mobile-card-head"><div><p class="person-name">{{ $siswa->nama_lengkap }}</p><p class="person-meta">{{ $siswa->anggotaKelas->first()?->kelas?->nama?:'-' }}</p></div><span class="badge badge-warning">{{ max(0,(int)$siswa->total_poin) }} poin</span></div><a class="button button-muted button-sm" style="margin-top:10px" href="{{ route('laporan-pembinaan-siswa.index',['kata_kunci'=>$siswa->nisn?:$siswa->nama_lengkap]) }}">Riwayat</a></article>@endforeach</div></section>
    @if($daftarSiswa->hasPages())<nav class="pagination-simple"><span>Halaman {{ $daftarSiswa->currentPage() }} dari {{ $daftarSiswa->lastPage() }}</span><div class="actions">@if($daftarSiswa->onFirstPage())<span class="button button-muted">Sebelumnya</span>@else<a href="{{ $daftarSiswa->previousPageUrl() }}" class="button button-muted">Sebelumnya</a>@endif @if($daftarSiswa->hasMorePages())<a href="{{ $daftarSiswa->nextPageUrl() }}" class="button button-muted">Berikutnya</a>@endif</div></nav>@endif
@endsection
