org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Plugin Android berada di Pub Cache drive C:, sedangkan project berada di D:.
# Incremental Kotlin tidak dapat membuat path relatif lintas drive pada Windows.
kotlin.incremental=false
