@extends('layouts.app')
@section('title', 'Detail Kegiatan Ibadah - NUSA')
@section('content')
    <div class="page-header"><div><p class="eyebrow">Kehadiran Siswa</p><h1 class="page-title">{{ $kegiatanIbadah->nama }}</h1><p class="page-subtitle">{{ $kegiatanIbadah->keterangan ?: 'Kegiatan ibadah siswa.' }}</p></div><div class="actions"><a href="{{ route('kegiatan-ibadah.index') }}" class="button button-muted">Kembali</a><a href="{{ route('kegiatan-ibadah.edit',$kegiatanIbadah) }}" class="button button-dark">Edit</a></div></div>
    @if(session('berhasil'))<div class="alert">{{ session('berhasil') }}</div>@endif
    <div class="detail-shell">
        <aside class="panel panel-pad"><h2 class="panel-title">Informasi</h2><dl class="quick-facts"><div><dt>Kode</dt><dd>{{ $kegiatanIbadah->kode }}</dd></div><div><dt>Peserta</dt><dd>{{ $kegiatanIbadah->labelCakupanPeserta() }}</dd></div><div><dt>Status</dt><dd><span class="badge {{ $kegiatanIbadah->aktif ? 'badge-active' : 'badge-inactive' }}">{{ $kegiatanIbadah->aktif ? 'Aktif' : 'Nonaktif' }}</span></dd></div><div><dt>Jumlah jadwal</dt><dd>{{ $kegiatanIbadah->jadwal->where('aktif',true)->count() }} aktif</dd></div></dl></aside>
        <section class="panel"><div class="panel-pad" style="border-bottom:1px solid var(--line);"><div class="section-heading"><div><h2 class="panel-title">Jadwal Kegiatan</h2><p class="help-text">Jadwal yang pernah ditetapkan untuk kegiatan ini.</p></div><a href="{{ route('jadwal-kegiatan-ibadah.create',['kegiatan_ibadah_id'=>$kegiatanIbadah->id]) }}" class="button button-primary button-sm">Tambah jadwal</a></div></div><div class="table-wrap"><table class="employee-table"><thead><tr><th>Tahun</th><th>Hari</th><th>Pelaksanaan</th><th>Waktu scan</th><th>Status</th></tr></thead><tbody>@forelse($kegiatanIbadah->jadwal as $jadwal)<tr><td>{{ $jadwal->tahunPelajaran?->nama }}</td><td>{{ $jadwal->labelHari() }}</td><td>{{ $jadwal->formatJam($jadwal->jam_pelaksanaan) }}</td><td>{{ $jadwal->rentangScan() }}</td><td><span class="badge {{ $jadwal->aktif ? 'badge-active' : 'badge-inactive' }}">{{ $jadwal->aktif ? 'Aktif' : 'Nonaktif' }}</span></td></tr>@empty<tr><td colspan="5" class="empty-state">Belum ada jadwal kegiatan.</td></tr>@endforelse</tbody></table></div></section>
    </div>
@endsection
