@extends('layouts.app')
@section('title', ($alumni->exists ? 'Edit' : 'Tambah').' Alumni - NUSA')
@section('alumni-actions')<a class="button button-muted" href="{{ $alumni->exists ? route('alumni-humas.show', $alumni) : route('alumni-humas.index') }}">Kembali</a>@endsection
@section('content')
<div class="publikasi-page alumni-page">
    @include('alumni-humas._header', ['judulHalaman' => $alumni->exists ? 'Edit alumni' : 'Tambah alumni'])
    <form method="POST" action="{{ $alumni->exists ? route('alumni-humas.update', $alumni) : route('alumni-humas.store') }}" data-alumni-form data-agenda-submit>
        @csrf
        @if($alumni->exists)@method('PUT')<input type="hidden" name="versi" value="{{ old('versi', $alumni->versi) }}">@else<input type="hidden" name="token_pembuatan" value="{{ old('token_pembuatan', $tokenPembuatan) }}">@endif
        <section class="agenda-section"><h2>Identitas alumni</h2><fieldset class="alumni-mode"><legend>Sumber identitas</legend><label><input type="radio" name="metode" value="manual" @checked(!$sumberSiswa)>Input alumni lama</label><label><input type="radio" name="metode" value="siswa" @checked($sumberSiswa)>Pilih siswa NUSA</label></fieldset>
            <input type="hidden" id="siswa_id" name="siswa_id" value="{{ $sumberSiswa['id'] ?? '' }}">
            <div data-source-panel @if(!$sumberSiswa) hidden @endif><div class="alumni-search"><div class="field"><label for="cari_siswa">Cari siswa (nama / NIS / NISN)</label><input class="input" id="cari_siswa" maxlength="120" autocomplete="off"></div><button type="button" class="button button-muted" data-cari-siswa>Cari siswa</button></div><p class="agenda-muted" data-source-state role="status" aria-live="polite"></p><ul class="alumni-source-results" data-source-results></ul><button type="button" class="button button-muted" data-source-more hidden>Muat berikutnya</button><div class="alumni-source-selected" data-source-selected>{{ $sumberSiswa['nama_lengkap'] ?? '' }}</div></div>
            <div class="agenda-field-grid">
                <div class="field span-2"><label for="nama_lengkap">Nama lengkap</label><input class="input" id="nama_lengkap" name="nama_lengkap" maxlength="180" value="{{ old('nama_lengkap', $alumni->nama_lengkap) }}" required data-identity></div>
                @foreach(['nis' => ['NIS (opsional)', 30], 'nisn' => ['NISN (opsional)', 10]] as $key => [$label, $max])<div class="field"><label for="{{ $key }}">{{ $label }}</label><input class="input" id="{{ $key }}" name="{{ $key }}" maxlength="{{ $max }}" value="{{ old($key, $alumni->$key) }}" data-identity @if($key === 'nisn')inputmode="numeric" pattern="[0-9]{10}"@endif></div>@endforeach
                <div class="field"><label for="jenis_kelamin">Jenis kelamin</label><select class="select" id="jenis_kelamin" name="jenis_kelamin"><option value="">Belum tercatat</option>@foreach(['L' => 'Laki-laki', 'P' => 'Perempuan'] as $kode => $nama)<option value="{{ $kode }}" @selected(old('jenis_kelamin', $alumni->jenis_kelamin) === $kode)>{{ $nama }}</option>@endforeach</select></div>
                <div class="field"><label for="tahun_masuk">Tahun masuk (opsional)</label><input type="number" class="input" id="tahun_masuk" name="tahun_masuk" min="1900" max="{{ today()->year }}" step="1" value="{{ old('tahun_masuk', $alumni->tahun_masuk) }}"></div>
            </div>
        </section>
        <section class="agenda-section"><h2>Kelulusan</h2><div class="agenda-field-grid">
            <div class="field" data-member-panel @if(!$sumberSiswa) hidden @endif><label for="anggota_kelas_id">Riwayat kelas IX (opsional)</label><select class="select" id="anggota_kelas_id" name="anggota_kelas_id"><option value="">Tidak dikaitkan</option>@foreach($sumberSiswa['kelas'] ?? [] as $k)<option value="{{ $k['id'] }}" @selected((string)old('anggota_kelas_id', $alumni->anggota_kelas_id) === (string)$k['id']) data-nama="{{ $k['nama'] }}" data-tahun="{{ $k['tahun_lulus'] }}">{{ $k['nama'] }} - {{ $k['tahun_pelajaran'] }}</option>@endforeach</select></div>
            <div class="field"><label for="kelas_terakhir">Kelas terakhir (opsional)</label><input class="input" id="kelas_terakhir" name="kelas_terakhir" maxlength="80" value="{{ old('kelas_terakhir', $alumni->kelas_terakhir) }}"></div>
            <div class="field"><label for="tahun_lulus">Angkatan (tahun lulus)</label><input type="number" class="input" id="tahun_lulus" name="tahun_lulus" min="1900" max="{{ today()->year }}" step="1" value="{{ old('tahun_lulus', $alumni->tahun_lulus) }}" required></div>
            <div class="field"><label for="tanggal_lulus">Tanggal lulus (opsional)</label><input type="date" class="input" id="tanggal_lulus" name="tanggal_lulus" max="{{ today()->format('Y-m-d') }}" value="{{ old('tanggal_lulus', $alumni->tanggal_lulus?->format('Y-m-d')) }}"></div>
            <div class="field"><label for="status">Status data</label><select class="select" id="status" name="status" required>@foreach(\App\Models\AlumniHumas::STATUS as $kode => $nama)<option value="{{ $kode }}" @selected(old('status', $alumni->status) === $kode)>{{ $nama }}</option>@endforeach</select></div>
        </div><label class="alumni-check"><input type="checkbox" name="konfirmasi_lulus" value="1" @checked(old('konfirmasi_lulus', $alumni->exists)) required>Kelulusan alumni ini sudah dipastikan.</label></section>
        <section class="agenda-section"><h2>Penelusuran sekolah lanjutan</h2><div class="agenda-field-grid"><div class="field"><label for="status_penelusuran">Status penelusuran</label><select class="select" id="status_penelusuran" name="status_penelusuran" required>@foreach(\App\Models\AlumniHumas::PENELUSURAN as $kode => $nama)<option value="{{ $kode }}" @selected(old('status_penelusuran', $alumni->status_penelusuran) === $kode)>{{ $nama }}</option>@endforeach</select></div><div class="field" data-trace-date><label for="tanggal_penelusuran">Tanggal penelusuran</label><input type="date" class="input" id="tanggal_penelusuran" name="tanggal_penelusuran" max="{{ today()->format('Y-m-d') }}" value="{{ old('tanggal_penelusuran', $alumni->tanggal_penelusuran?->format('Y-m-d')) }}"></div></div>
            <fieldset class="agenda-field-grid" data-school-fields style="border:0;padding:0;margin:16px 0 0"><div class="field"><label for="jenis_sekolah">Jenis sekolah</label><select class="select" id="jenis_sekolah" name="jenis_sekolah"><option value="">Pilih jenis sekolah</option>@foreach(\App\Models\AlumniHumas::SEKOLAH as $kode => $nama)<option value="{{ $kode }}" @selected(old('jenis_sekolah', $alumni->jenis_sekolah) === $kode)>{{ $nama }}</option>@endforeach</select></div><div class="field"><label for="nama_sekolah">Nama sekolah lanjutan</label><input class="input" id="nama_sekolah" name="nama_sekolah" maxlength="180" value="{{ old('nama_sekolah', $alumni->nama_sekolah) }}"></div><div class="field"><label for="kota_sekolah">Kota / kabupaten sekolah (opsional)</label><input class="input" id="kota_sekolah" name="kota_sekolah" maxlength="120" value="{{ old('kota_sekolah', $alumni->kota_sekolah) }}"></div><div class="field"><label for="jurusan">Jurusan / program (opsional)</label><input class="input" id="jurusan" name="jurusan" maxlength="180" value="{{ old('jurusan', $alumni->jurusan) }}"></div></fieldset>
        </section>
        <section class="agenda-section"><h2>Kontak & catatan privat</h2><div class="agenda-field-grid"><div class="field"><label for="nomor_wa">Nomor WA alumni (opsional)</label><input type="tel" class="input" id="nomor_wa" name="nomor_wa" maxlength="30" value="{{ old('nomor_wa', $alumni->nomor_wa) }}"></div><div class="field"><label for="email">Email alumni (opsional)</label><input type="email" class="input" id="email" name="email" maxlength="254" value="{{ old('email', $alumni->email) }}"></div><div class="field span-2"><label for="catatan_penelusuran" data-trace-note-label>Catatan penelusuran (privat)</label><textarea class="textarea" id="catatan_penelusuran" name="catatan_penelusuran" rows="3" maxlength="3000">{{ old('catatan_penelusuran', $alumni->catatan_penelusuran) }}</textarea></div>
            @if($alumni->exists)<div class="field span-2"><label for="catatan_perubahan">Alasan perubahan</label><textarea class="textarea" id="catatan_perubahan" name="catatan_perubahan" rows="2" minlength="5" maxlength="2000" required>{{ old('catatan_perubahan') }}</textarea></div>@endif
        </div></section><div class="agenda-actions"><button type="submit" class="button button-primary">Simpan alumni</button><a class="button button-muted" href="{{ route('alumni-humas.index') }}">Batal</a></div>
    </form>
</div>
@include('alumni-humas._scripts')
@include('agenda-humas._scripts')
@endsection
