@extends('layouts.app')
@section('title', 'Edit Jadwal Ibadah - NUSA')
@section('content')
    <div class="page-header"><div><p class="eyebrow">Kehadiran Siswa</p><h1 class="page-title">Edit Jadwal {{ $jadwalKegiatanIbadah->labelHari() }}</h1><p class="page-subtitle">{{ $jadwalKegiatanIbadah->kegiatanIbadah?->nama }} &middot; {{ $jadwalKegiatanIbadah->tahunPelajaran?->nama }}</p></div><a href="{{ route('jadwal-kegiatan-ibadah.index',['tahun_pelajaran_id'=>$jadwalKegiatanIbadah->tahun_pelajaran_id,'kegiatan_ibadah_id'=>$jadwalKegiatanIbadah->kegiatan_ibadah_id]) }}" class="button button-muted">Kembali</a></div>
    @if($errors->any())<div class="alert alert-danger"><strong>Ada data yang perlu diperbaiki.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form action="{{ route('jadwal-kegiatan-ibadah.update',$jadwalKegiatanIbadah) }}" method="POST">@csrf @method('PUT')
        <div class="form-shell"><aside class="panel panel-pad"><h2 class="panel-title">Status jadwal</h2><p class="help-text">Aktifkan kembali jadwal yang sebelumnya dinonaktifkan.</p><label class="status-toggle"><span><span class="form-label" style="margin-bottom:0;">Jadwal aktif</span><span class="help-text">Dipakai pada hari {{ $jadwalKegiatanIbadah->labelHari() }}</span></span><input type="hidden" name="aktif" value="0"><input type="checkbox" name="aktif" value="1" @checked(old('aktif',$jadwalKegiatanIbadah->aktif))></label></aside><div class="section-stack"><section class="panel panel-pad"><h2 class="panel-title">Waktu Kegiatan</h2><div class="form-grid"><div class="field"><label for="jam_scan_mulai">Mulai scan</label><input id="jam_scan_mulai" name="jam_scan_mulai" type="time" class="input" value="{{ old('jam_scan_mulai',substr($jadwalKegiatanIbadah->jam_scan_mulai,0,5)) }}" required></div><div class="field"><label for="jam_pelaksanaan">Waktu pelaksanaan</label><input id="jam_pelaksanaan" name="jam_pelaksanaan" type="time" class="input" value="{{ old('jam_pelaksanaan',substr($jadwalKegiatanIbadah->jam_pelaksanaan,0,5)) }}" required></div><div class="field"><label for="jam_scan_selesai">Batas akhir scan</label><input id="jam_scan_selesai" name="jam_scan_selesai" type="time" class="input" value="{{ old('jam_scan_selesai',substr($jadwalKegiatanIbadah->jam_scan_selesai,0,5)) }}" required></div><div class="field span-2"><label for="keterangan">Keterangan</label><textarea id="keterangan" name="keterangan" class="textarea" rows="3">{{ old('keterangan',$jadwalKegiatanIbadah->keterangan) }}</textarea></div></div></section><div class="form-actions"><a href="{{ route('jadwal-kegiatan-ibadah.index',['tahun_pelajaran_id'=>$jadwalKegiatanIbadah->tahun_pelajaran_id,'kegiatan_ibadah_id'=>$jadwalKegiatanIbadah->kegiatan_ibadah_id]) }}" class="button button-muted">Batal</a><button type="submit" class="button button-primary">Simpan perubahan</button></div></div></div>
    </form>
@endsection
