<?php

return [
    [
        'kode' => 'data-sekolah',
        'label' => 'Data Sekolah',
        'deskripsi' => 'Data induk sekolah, pegawai, siswa, kelas, dan identitas.',
        'ikon' => 'school',
        'items' => [
            ['kode' => 'tahun-pelajaran', 'label' => 'Tahun Pelajaran', 'inisial' => 'TP', 'subkelompok' => 'Periode Akademik', 'izin' => ['tahun_pelajaran.lihat', 'tahun_pelajaran.kelola'], 'status' => 'tersedia', 'rute' => '/tahun-pelajaran'],
            ['kode' => 'pegawai', 'label' => 'Pegawai', 'inisial' => 'PG', 'subkelompok' => 'Pegawai', 'izin' => ['pegawai.lihat', 'pegawai.kelola'], 'status' => 'tersedia', 'rute' => '/pegawai'],
            ['kode' => 'siswa', 'label' => 'Siswa', 'inisial' => 'SW', 'subkelompok' => 'Siswa dan Kelas', 'izin' => ['siswa.lihat', 'siswa.kelola'], 'status' => 'tersedia', 'rute' => '/siswa'],
            ['kode' => 'kelas', 'label' => 'Kelas', 'inisial' => 'KL', 'subkelompok' => 'Siswa dan Kelas', 'izin' => ['kelas.lihat', 'kelas.kelola'], 'status' => 'tersedia', 'rute' => '/kelas'],
            ['kode' => 'penempatan-siswa', 'label' => 'Penempatan Siswa', 'inisial' => 'PS', 'subkelompok' => 'Siswa dan Kelas', 'izin' => ['kelas.lihat', 'kelas.kelola']],
            ['kode' => 'kenaikan-kelas', 'label' => 'Kenaikan Kelas', 'inisial' => 'KK', 'subkelompok' => 'Siswa dan Kelas', 'izin' => 'kenaikan_kelas.kelola'],
            ['kode' => 'foto-identitas', 'label' => 'Foto Identitas', 'inisial' => 'FI', 'subkelompok' => 'Identitas dan Kartu', 'izin' => ['siswa.kelola', 'pegawai.kelola']],
            ['kode' => 'kartu-pegawai', 'label' => 'Kartu Pegawai', 'inisial' => 'KG', 'subkelompok' => 'Identitas dan Kartu', 'izin' => 'pegawai.lihat'],
            ['kode' => 'kartu-pelajar', 'label' => 'Kartu Pelajar', 'inisial' => 'KP', 'subkelompok' => 'Identitas dan Kartu', 'izin' => ['kartu_pelajar.lihat', 'kartu_pelajar.cetak']],
        ],
    ],
    [
        'kode' => 'akademik',
        'label' => 'Akademik',
        'deskripsi' => 'Pembelajaran, penilaian, survei, dan perangkat ajar.',
        'ikon' => 'academic',
        'items' => [
            ['kode' => 'mata-pelajaran', 'label' => 'Mata Pelajaran', 'inisial' => 'MP', 'subkelompok' => 'Pembelajaran', 'izin' => ['mata_pelajaran.lihat', 'mata_pelajaran.kelola'], 'status' => 'tersedia', 'rute' => '/mata-pelajaran'],
            ['kode' => 'guru-mata-pelajaran', 'label' => 'Guru Mata Pelajaran', 'inisial' => 'GM', 'subkelompok' => 'Pembelajaran', 'izin' => ['guru_mapel.lihat', 'guru_mapel.kelola'], 'status' => 'tersedia', 'rute' => '/guru-mata-pelajaran'],
            ['kode' => 'jadwal-mengajar-saya', 'label' => 'Jadwal Mengajar Saya', 'inisial' => 'JS', 'subkelompok' => 'Pembelajaran', 'izin' => 'jadwal.pribadi', 'pegawai_only' => true],
            ['kode' => 'jam-pelajaran', 'label' => 'Jam Pelajaran', 'inisial' => 'JM', 'subkelompok' => 'Pembelajaran', 'izin' => ['jadwal.lihat', 'jadwal.kelola'], 'administrator_only' => true, 'status' => 'tersedia', 'rute' => '/jam-pelajaran'],
            ['kode' => 'jadwal-pelajaran', 'label' => 'Jadwal Pelajaran', 'inisial' => 'JP', 'subkelompok' => 'Pembelajaran', 'izin' => ['jadwal.lihat', 'jadwal.kelola'], 'status' => 'tersedia', 'rute' => '/kelas?mode=jadwal'],
            ['kode' => 'skema-bobot-nilai', 'label' => 'Skema Bobot Nilai', 'inisial' => 'BN', 'subkelompok' => 'Penilaian', 'izin' => 'nilai.skema_kelola'],
            ['kode' => 'input-nilai', 'label' => 'Input Nilai', 'inisial' => 'IN', 'subkelompok' => 'Penilaian', 'izin' => 'nilai.input'],
            ['kode' => 'rekap-nilai-rapor', 'label' => 'Rekap Nilai Rapor', 'inisial' => 'RR', 'subkelompok' => 'Penilaian', 'izin' => 'nilai.rekap'],
            ['kode' => 'pernyataan-survei', 'label' => 'Pernyataan Survei', 'inisial' => 'SV', 'subkelompok' => 'Penilaian', 'izin' => 'survei.pertanyaan_kelola'],
            ['kode' => 'hasil-survei-saya', 'label' => 'Hasil Survei Saya', 'inisial' => 'HS', 'subkelompok' => 'Penilaian', 'izin' => 'survei.hasil_pribadi', 'pegawai_only' => true],
            ['kode' => 'monitoring-survei', 'label' => 'Monitoring Survei', 'inisial' => 'MS', 'subkelompok' => 'Penilaian', 'izin' => 'survei.monitor'],
            ['kode' => 'perangkat-ajar-saya', 'label' => 'Perangkat Ajar Saya', 'inisial' => 'PS', 'subkelompok' => 'Perangkat Ajar', 'izin' => 'perangkat_ajar.upload', 'pegawai_only' => true],
            ['kode' => 'pemeriksaan-perangkat-ajar', 'label' => 'Pemeriksaan Perangkat Ajar', 'inisial' => 'PP', 'subkelompok' => 'Perangkat Ajar', 'izin' => ['perangkat_ajar.lihat', 'perangkat_ajar.periksa']],
            ['kode' => 'jenis-perangkat-ajar', 'label' => 'Jenis Perangkat Ajar', 'inisial' => 'PA', 'subkelompok' => 'Perangkat Ajar', 'izin' => 'perangkat_ajar.jenis_kelola'],
        ],
    ],
    [
        'kode' => 'ujian-asesmen',
        'label' => 'Ujian & Asesmen',
        'deskripsi' => 'Pusat pengelolaan asesmen dan ujian CBT.',
        'ikon' => 'quiz',
        'items' => [
            ['kode' => 'pusat-cbt', 'label' => 'Pusat CBT', 'inisial' => 'CB', 'subkelompok' => 'CBT', 'izin' => ['cbt.lihat', 'cbt.kelola', 'cbt.soal_kelola', 'cbt.presensi', 'cbt.asesmen_kelola', 'cbt.panitia', 'cbt.terpusat_lihat']],
        ],
    ],
    [
        'kode' => 'kehadiran',
        'label' => 'Kehadiran',
        'deskripsi' => 'Piket, kegiatan ibadah, serta presensi siswa dan pegawai.',
        'ikon' => 'attendance',
        'items' => [
            ['kode' => 'jadwal-guru-piket', 'label' => 'Jadwal Guru Piket', 'inisial' => 'GP', 'subkelompok' => 'Guru Piket', 'izin' => 'piket_guru.kelola'],
            ['kode' => 'kegiatan-ibadah', 'label' => 'Kegiatan Ibadah', 'inisial' => 'KI', 'subkelompok' => 'Ibadah Siswa', 'izin' => 'ibadah.pengaturan_kelola'],
            ['kode' => 'jadwal-ibadah', 'label' => 'Jadwal Ibadah', 'inisial' => 'JI', 'subkelompok' => 'Ibadah Siswa', 'izin' => 'ibadah.pengaturan_kelola'],
            ['kode' => 'pengaturan-berhalangan', 'label' => 'Pengaturan Berhalangan', 'inisial' => 'PB', 'subkelompok' => 'Ibadah Siswa', 'izin' => 'ibadah.pengaturan_kelola'],
            ['kode' => 'scan-ibadah-siswa', 'label' => 'Scan Ibadah Siswa', 'inisial' => 'SI', 'subkelompok' => 'Ibadah Siswa', 'izin' => 'ibadah.scan'],
            ['kode' => 'rekap-ibadah-siswa', 'label' => 'Rekap Ibadah Siswa', 'inisial' => 'RI', 'subkelompok' => 'Ibadah Siswa', 'izin' => 'ibadah.rekap'],
            ['kode' => 'ringkasan-ibadah-bulanan', 'label' => 'Ringkasan Ibadah Bulanan', 'inisial' => 'BI', 'subkelompok' => 'Ibadah Siswa', 'izin' => 'ibadah.rekap'],
            ['kode' => 'pengaturan-presensi-siswa', 'label' => 'Pengaturan Presensi Siswa', 'inisial' => 'PA', 'subkelompok' => 'Presensi Siswa', 'izin' => 'absensi.pengaturan_kelola'],
            ['kode' => 'scan-presensi-siswa', 'label' => 'Scan Presensi Siswa', 'inisial' => 'SS', 'subkelompok' => 'Presensi Siswa', 'izin' => 'absensi.scan'],
            ['kode' => 'rekap-presensi-siswa', 'label' => 'Rekap Presensi Siswa', 'inisial' => 'RS', 'subkelompok' => 'Presensi Siswa', 'izin' => ['absensi.lihat', 'absensi.koreksi', 'absensi.laporan']],
            ['kode' => 'laporan-presensi-siswa', 'label' => 'Laporan Presensi Siswa', 'inisial' => 'LS', 'subkelompok' => 'Presensi Siswa', 'izin' => 'absensi.laporan'],
            ['kode' => 'pengaturan-presensi-pegawai', 'label' => 'Pengaturan Presensi Pegawai', 'inisial' => 'PA', 'subkelompok' => 'Presensi Pegawai', 'izin' => 'absensi.pengaturan_kelola'],
            ['kode' => 'scan-presensi-pegawai', 'label' => 'Scan Presensi Pegawai', 'inisial' => 'SP', 'subkelompok' => 'Presensi Pegawai', 'izin' => 'absensi.scan'],
            ['kode' => 'rekap-presensi-pegawai', 'label' => 'Rekap Presensi Pegawai', 'inisial' => 'RP', 'subkelompok' => 'Presensi Pegawai', 'izin' => ['absensi.lihat', 'absensi.koreksi', 'absensi.laporan', 'absensi_pegawai.pribadi']],
            ['kode' => 'laporan-presensi-pegawai', 'label' => 'Laporan Presensi Pegawai', 'inisial' => 'LP', 'subkelompok' => 'Presensi Pegawai', 'izin' => ['absensi.laporan', 'absensi_pegawai.pribadi']],
        ],
    ],
    [
        'kode' => 'kesiswaan-bk',
        'label' => 'Kesiswaan & BK',
        'deskripsi' => 'Pembinaan, poin, pendampingan, dan pemantauan siswa.',
        'ikon' => 'counseling',
        'items' => [
            ['kode' => 'pemeriksaan-pengesahan', 'label' => 'Pemeriksaan & Pengesahan', 'inisial' => 'VP', 'subkelompok' => 'Operasional', 'izin' => ['poin_siswa.lihat', 'poin_siswa.verifikasi_bk', 'poin_siswa.sahkan_wakil']],
            ['kode' => 'daftar-laporan-siswa', 'label' => 'Daftar Laporan Siswa', 'inisial' => 'LS', 'subkelompok' => 'Operasional', 'izin' => ['bk.lihat', 'bk.kelola', 'poin_siswa.lapor', 'poin_siswa.lihat', 'poin_siswa.verifikasi_bk']],
            ['kode' => 'pendampingan-siswa', 'label' => 'Pendampingan Siswa', 'inisial' => 'PD', 'subkelompok' => 'Operasional', 'izin' => 'poin_siswa.lihat'],
            ['kode' => 'pelaksanaan-sanksi-siswa', 'label' => 'Pelaksanaan Sanksi Siswa', 'inisial' => 'PS', 'subkelompok' => 'Operasional', 'izin' => ['poin_siswa.lihat', 'poin_siswa.sanksi_kelola']],
            ['kode' => 'peringatan-dini-siswa', 'label' => 'Peringatan Dini Siswa', 'inisial' => 'PD', 'subkelompok' => 'Monitoring', 'izin' => 'poin_siswa.lihat'],
            ['kode' => 'rekap-poin-siswa', 'label' => 'Rekap Poin Siswa', 'inisial' => 'RP', 'subkelompok' => 'Monitoring', 'izin' => 'poin_siswa.lihat'],
            ['kode' => 'penghargaan-pengurangan-poin', 'label' => 'Penghargaan & Pengurangan Poin', 'inisial' => 'PH', 'subkelompok' => 'Operasional', 'izin' => ['poin_siswa.reward_kelola', 'poin_siswa.putus_konflik']],
            ['kode' => 'penugasan-guru-wali', 'label' => 'Penugasan Guru Wali', 'inisial' => 'GW', 'subkelompok' => 'Guru Wali', 'izin' => 'guru_wali.kelola'],
            ['kode' => 'jenis-pelanggaran-poin', 'label' => 'Jenis Pelanggaran & Poin', 'inisial' => 'JP', 'subkelompok' => 'Pengaturan', 'izin' => 'poin_siswa.pengaturan'],
            ['kode' => 'aturan-sanksi-poin', 'label' => 'Aturan Sanksi Poin', 'inisial' => 'AS', 'subkelompok' => 'Pengaturan', 'izin' => 'poin_siswa.pengaturan'],
            ['kode' => 'poin-keterlambatan', 'label' => 'Poin Keterlambatan', 'inisial' => 'PK', 'subkelompok' => 'Pengaturan', 'izin' => 'poin_siswa.pengaturan'],
            ['kode' => 'peringatan-dini-poin', 'label' => 'Peringatan Dini Poin', 'inisial' => 'PD', 'subkelompok' => 'Pengaturan', 'izin' => 'poin_siswa.pengaturan'],
            ['kode' => 'batas-proses-pelanggaran', 'label' => 'Batas Proses Pelanggaran', 'inisial' => 'BP', 'subkelompok' => 'Pengaturan', 'izin' => 'poin_siswa.pengaturan'],
            ['kode' => 'kategori-pembinaan-non-poin', 'label' => 'Kategori Pembinaan Non-Poin', 'inisial' => 'KP', 'subkelompok' => 'Pengaturan', 'izin' => 'bk.kelola'],
        ],
    ],
    [
        'kode' => 'sarana-prasarana',
        'label' => 'Sarana Prasarana',
        'deskripsi' => 'Inventaris, stok, peminjaman, pengajuan, dan laporan barang.',
        'ikon' => 'inventory',
        'items' => [
            ['kode' => 'katalog-barang', 'label' => 'Katalog Barang', 'inisial' => 'KB', 'subkelompok' => 'Layanan Pegawai', 'izin' => null],
            ['kode' => 'pengajuan-saya', 'label' => 'Pengajuan Saya', 'inisial' => 'PS', 'subkelompok' => 'Layanan Pegawai', 'izin' => null, 'pegawai_only' => true],
            ['kode' => 'dashboard-sarpras', 'label' => 'Dashboard Sarpras', 'inisial' => 'DS', 'subkelompok' => 'Ringkasan', 'izin' => ['barang.lihat', 'barang.kelola', 'barang.peminjaman_kelola']],
            ['kode' => 'inventaris-barang', 'label' => 'Inventaris Barang', 'inisial' => 'IB', 'subkelompok' => 'Inventaris', 'izin' => ['barang.lihat', 'barang.kelola']],
            ['kode' => 'unit-aset', 'label' => 'Unit Aset', 'inisial' => 'UA', 'subkelompok' => 'Inventaris', 'izin' => ['barang.lihat', 'barang.kelola']],
            ['kode' => 'label-inventaris', 'label' => 'Label Inventaris', 'inisial' => 'LI', 'subkelompok' => 'Inventaris', 'izin' => ['barang.lihat', 'barang.kelola']],
            ['kode' => 'barang-datang', 'label' => 'Barang Datang', 'inisial' => 'BD', 'subkelompok' => 'Stok Barang', 'izin' => ['barang.lihat', 'barang.kelola']],
            ['kode' => 'saldo-stok', 'label' => 'Saldo Stok', 'inisial' => 'SS', 'subkelompok' => 'Stok Barang', 'izin' => ['barang.lihat', 'barang.kelola']],
            ['kode' => 'mutasi-stok', 'label' => 'Mutasi Stok', 'inisial' => 'MS', 'subkelompok' => 'Stok Barang', 'izin' => ['barang.lihat', 'barang.kelola']],
            ['kode' => 'peminjaman-barang', 'label' => 'Peminjaman Barang', 'inisial' => 'PB', 'subkelompok' => 'Peminjaman', 'izin' => ['barang.lihat', 'barang.peminjaman_kelola']],
            ['kode' => 'pengajuan-barang', 'label' => 'Pengajuan Barang', 'inisial' => 'PJ', 'subkelompok' => 'Peminjaman', 'izin' => 'barang.peminjaman_kelola'],
            ['kode' => 'pengembalian-barang', 'label' => 'Pengembalian Barang', 'inisial' => 'KM', 'subkelompok' => 'Peminjaman', 'izin' => 'barang.peminjaman_kelola'],
            ['kode' => 'rekap-peminjaman', 'label' => 'Rekap Peminjaman', 'inisial' => 'RP', 'subkelompok' => 'Peminjaman', 'izin' => ['barang.lihat', 'barang.peminjaman_kelola']],
            ['kode' => 'laporan-inventaris', 'label' => 'Laporan Inventaris', 'inisial' => 'LI', 'subkelompok' => 'Laporan', 'izin' => ['barang.lihat', 'barang.kelola']],
            ['kode' => 'kategori-barang', 'label' => 'Kategori Barang', 'inisial' => 'KB', 'subkelompok' => 'Pengaturan', 'izin' => ['barang.lihat', 'barang.kelola']],
            ['kode' => 'satuan-barang', 'label' => 'Satuan Barang', 'inisial' => 'SB', 'subkelompok' => 'Pengaturan', 'izin' => ['barang.lihat', 'barang.kelola']],
            ['kode' => 'lokasi-barang', 'label' => 'Lokasi Barang', 'inisial' => 'LK', 'subkelompok' => 'Pengaturan', 'izin' => ['barang.lihat', 'barang.kelola']],
            ['kode' => 'sumber-perolehan', 'label' => 'Sumber Perolehan', 'inisial' => 'SP', 'subkelompok' => 'Pengaturan', 'izin' => ['barang.lihat', 'barang.kelola']],
            ['kode' => 'pengaturan-inventaris', 'label' => 'Pengaturan Inventaris', 'inisial' => 'PI', 'subkelompok' => 'Pengaturan', 'izin' => 'barang.kelola'],
        ],
    ],
    [
        'kode' => 'sistem',
        'label' => 'Sistem',
        'deskripsi' => 'Akun, role, hak akses, aktivitas login, dan pencadangan.',
        'ikon' => 'security',
        'items' => [
            ['kode' => 'akun-pegawai', 'label' => 'Akun Pegawai', 'inisial' => 'AP', 'izin' => ['akun.lihat', 'akun.kelola'], 'status' => 'tersedia', 'rute' => '/akun-pegawai'],
            ['kode' => 'akun-siswa', 'label' => 'Akun Siswa', 'inisial' => 'AS', 'izin' => ['akun_siswa.lihat', 'akun_siswa.kelola', 'akun_siswa.cetak']],
            ['kode' => 'akun-orang-tua', 'label' => 'Akun Orang Tua', 'inisial' => 'AO', 'izin' => ['akun_orang_tua.lihat', 'akun_orang_tua.kelola', 'akun_orang_tua.cetak']],
            ['kode' => 'role-hak-akses', 'label' => 'Role & Hak Akses', 'inisial' => 'RA', 'izin' => ['peran.lihat', 'peran.kelola']],
            ['kode' => 'aktivitas-login', 'label' => 'Aktivitas Login', 'inisial' => 'AL', 'izin' => 'aktivitas_login.lihat'],
            ['kode' => 'backup-restore', 'label' => 'Backup & Restore', 'inisial' => 'BR', 'izin' => 'cadangan_database.kelola'],
        ],
    ],
];
