@extends('layouts.app')
@section('title', 'Komite Sekolah - NUSA')
@section('content')
@include('komite-humas._style')
<div class="publikasi-page komite-page">
    <div class="page-header"><div><p class="eyebrow">Humas</p><h1 class="page-title">Komite Sekolah</h1></div>@izin('komite_humas.kelola')<a class="button button-primary" href="{{ route('komite-humas.create') }}">Tambah kepengurusan</a>@endizin</div>
    @include('agenda-humas._messages')
    <div class="agenda-metrics">@foreach (['berjalan' => 'Kepengurusan berjalan', 'pengurus' => 'Pengurus aktif saat ini', 'draf' => 'Draf kepengurusan', 'berakhir' => 'Masa bakti telah berakhir'] as $key => $label)<div class="agenda-metric"><span>{{ $label }}</span><strong>{{ $statistik[$key] }}</strong></div>@endforeach</div>
    <section class="agenda-section"><form class="komite-filter" method="GET" action="{{ route('komite-humas.index') }}"><div class="field"><label for="kata_kunci">Cari kepengurusan</label><input class="input" id="kata_kunci" name="kata_kunci" maxlength="120" value="{{ $filter['kata_kunci'] ?? '' }}" placeholder="Periode, nama pengurus, atau nomor SK"></div><div class="field"><label for="status">Status</label><select class="select" id="status" name="status">@foreach (['semua' => 'Semua status'] + \App\Models\PeriodeKomiteHumas::STATUS as $value => $label)<option value="{{ $value }}" @selected(($filter['status'] ?? 'semua') === $value)>{{ $label }}</option>@endforeach</select></div><div class="field"><label for="masa">Masa bakti</label><select class="select" id="masa" name="masa"><option value="">Semua masa bakti</option>@foreach (\App\Models\PeriodeKomiteHumas::MASA as $value => $label)<option value="{{ $value }}" @selected(($filter['masa'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></div><div class="agenda-actions"><button class="button button-muted" type="submit">Tampilkan</button><a href="{{ route('komite-humas.index') }}">Reset</a></div></form></section>
    <ul class="komite-list">@forelse ($daftar as $periode)<li class="komite-row"><div><div class="komite-tags"><span class="komite-badge komite-badge--{{ $periode->status }}">{{ \App\Models\PeriodeKomiteHumas::STATUS[$periode->status] }}</span><span class="komite-badge komite-badge--{{ $periode->masaBakti() }}">{{ \App\Models\PeriodeKomiteHumas::MASA[$periode->masaBakti()] }}</span></div><h2><a href="{{ route('komite-humas.show', $periode) }}">{{ $periode->nama }}</a></h2><p class="agenda-muted">{{ $periode->tanggal_mulai->format('d-m-Y') }} s.d. {{ $periode->tanggal_selesai->format('d-m-Y') }}</p><p class="agenda-muted">SK: {{ $periode->nomor_sk ?: 'Belum diisi' }} &middot; {{ $periode->riwayat_dokumen_humas_id ? 'Berkas tersimpan' : 'Belum ada berkas' }}</p></div><div><p class="agenda-muted">Ketua</p><strong>{{ $periode->pengurus->first()?->nama ?: 'Belum diisi' }}</strong><p class="agenda-muted">{{ $periode->jumlah_pengurus }} pengurus aktif</p></div><div class="agenda-actions"><a class="button button-muted" href="{{ route('komite-humas.show', $periode) }}">Lihat kepengurusan</a></div></li>@empty<li class="agenda-empty"><strong>Belum ada kepengurusan yang sesuai.</strong></li>@endforelse</ul>
    {{ $daftar->links() }}
</div>
@endsection
