@extends('layouts.app')
@section('title', 'Kepengurusan Komite - NUSA')
@section('content')
@include('komite-humas._style')
<div class="publikasi-page komite-page">
    <div class="page-header"><div style="min-width:0"><p class="eyebrow">Humas / Komite Sekolah</p><h1 class="page-title">{{ $periode->nama }}</h1><div class="komite-tags"><span class="komite-badge komite-badge--{{ $periode->status }}">{{ \App\Models\PeriodeKomiteHumas::STATUS[$periode->status] }}</span><span class="komite-badge komite-badge--{{ $periode->masaBakti() }}">{{ \App\Models\PeriodeKomiteHumas::MASA[$periode->masaBakti()] }}</span></div></div><div class="actions"><a class="button button-muted" href="{{ route('komite-humas.index') }}">Daftar kepengurusan</a>@if ($manager)<a class="button button-primary" href="{{ route('komite-humas.edit', $periode) }}">Edit kepengurusan</a>@endif</div></div>
    @include('agenda-humas._messages')
    <section class="agenda-section"><h2>Periode & SK pengangkatan</h2>@include('komite-humas._rincian', ['dataPeriode' => $periode->snapshot()])
        <h3>Berkas SK</h3>@if ($bolehDokumen && $periode->berkas)<div class="komite-file"><strong>{{ $periode->berkas->nama_file_asli }}</strong><a href="{{ route('komite-humas.berkas', [$periode, $periode->berkas]) }}" target="_blank" rel="noopener">Buka SK</a><a href="{{ route('komite-humas.berkas', [$periode, $periode->berkas, 'unduh' => 1]) }}">Unduh</a></div>@else<p class="agenda-muted">{{ $periode->riwayat_dokumen_humas_id ? 'Berkas SK dibatasi sesuai izin dokumen Humas.' : 'Belum ada berkas SK.' }}</p>@endif
    </section>
    <section class="agenda-section"><h2>Susunan pengurus</h2><div class="komite-table-shell"><table class="komite-table komite-table--responsive"><thead><tr><th>Nama pengurus</th><th>Jabatan</th><th>Status pengurus</th>@if ($manager)<th>Kontak privat</th>@endif</tr></thead><tbody>@forelse ($pengurus as $p)<tr><td data-label="Nama">{{ $p->nama }}</td><td data-label="Jabatan">{{ \App\Models\PengurusKomiteHumas::JABATAN[$p->jabatan] }}</td><td data-label="Status"><span class="komite-badge komite-badge--{{ $p->aktif ? 'aktif' : 'arsip' }}">{{ $p->aktif ? 'Aktif' : 'Tidak aktif' }}</span></td>@if ($manager)<td data-label="Kontak privat">{{ $p->nomor_telepon ?: '-' }}</td>@endif</tr>@empty<tr><td colspan="{{ $manager ? 4 : 3 }}">Belum ada pengurus.</td></tr>@endforelse</tbody></table></div></section>
    <section class="agenda-section"><h2>Riwayat kepengurusan</h2><ul class="publikasi-history">@foreach ($riwayat as $item)<li><strong>{{ $item->aksi }}</strong><p class="agenda-muted">{{ $item->pengguna?->nama ?: 'Akun tidak tersedia' }} &middot; {{ $item->created_at->format('d-m-Y H:i') }} &middot; Versi {{ $item->versi + 1 }}</p>@if ($item->catatan_perubahan)<div class="agenda-text">{{ $item->catatan_perubahan }}</div>@endif<details><summary>Lihat susunan pada versi ini</summary><div class="publikasi-snapshot"><h3>{{ $item->snapshot['nama'] }}</h3>@include('komite-humas._rincian', ['dataPeriode' => $item->snapshot])<div class="komite-table-shell"><table class="komite-table komite-table--responsive komite-table--snapshot"><thead><tr><th>Nama</th><th>Jabatan</th><th>Status</th></tr></thead><tbody>@foreach ($item->snapshot['pengurus'] as $p)<tr><td data-label="Nama">{{ $p['nama'] }}</td><td data-label="Jabatan">{{ \App\Models\PengurusKomiteHumas::JABATAN[$p['jabatan']] }}</td><td data-label="Status">{{ $p['aktif'] ? 'Aktif' : 'Tidak aktif' }}</td></tr>@endforeach</tbody></table></div>@if ($bolehDokumen && $item->berkas)<div class="agenda-actions"><a href="{{ route('komite-humas.berkas', [$periode, $item->berkas]) }}" target="_blank" rel="noopener">SK versi ini: {{ $item->berkas->nama_file_asli }}</a></div>@endif</div></details></li>@endforeach</ul>{{ $riwayat->links() }}</section>
</div>
@endsection
