@extends('layouts.app')
@section('title','Pengurangan Poin Siswa - NUSA')
@section('content')
    <style>.reward-layout{display:grid;gap:20px;grid-template-columns:minmax(300px,.8fr) minmax(0,1.6fr)}@media(max-width:950px){.reward-layout{grid-template-columns:1fr}}</style>
    <div class="page-header"><div><p class="eyebrow">Kesiswaan & BK</p><h1 class="page-title">Pengurangan Poin/Reward</h1><p class="page-subtitle">Pengurangan diterapkan setelah disetujui dan tidak pernah membuat saldo poin menjadi negatif.</p></div><a href="{{ route('rekap-poin-siswa.index') }}" class="button button-muted">Rekap Poin</a></div>
    @if(session('berhasil'))<div class="alert">{{ session('berhasil') }}</div>@endif
    <div class="reward-layout">
        <form method="POST" action="{{ route('pengurangan-poin-siswa.store') }}" enctype="multipart/form-data" class="panel panel-pad">@csrf<h2 class="panel-title">Ajukan reward</h2><div class="field" style="margin-top:14px"><label for="siswa">Siswa</label><select id="siswa" name="siswa_id" class="select" required><option value="">Pilih siswa</option>@foreach($daftarSiswa as $siswa)<option value="{{ $siswa->id }}">{{ $siswa->nama_lengkap }} · {{ $siswa->nisn?:'-' }}</option>@endforeach</select></div><div class="field" style="margin-top:12px"><label for="tahun">Tahun pelajaran</label><select id="tahun" name="tahun_pelajaran_id" class="select" required>@foreach($daftarTahunPelajaran as $tahun)<option value="{{ $tahun->id }}" @selected((string)$tahunPelajaranId===(string)$tahun->id)>{{ $tahun->nama }}</option>@endforeach</select></div><div class="field" style="margin-top:12px"><label for="tanggal">Tanggal kegiatan</label><input id="tanggal" name="tanggal_kegiatan" type="date" value="{{ now()->toDateString() }}" class="input" required></div><div class="field" style="margin-top:12px"><label for="jenis">Kegiatan positif</label><select id="jenis" name="jenis_kegiatan" class="select" required><option>Juara lomba tingkat sekolah</option><option>Juara tingkat kota/kabupaten</option><option>Juara tingkat provinsi</option><option>Aktif organisasi</option><option>Hafalan Al-Qur'an/kegiatan keagamaan</option><option>Teladan disiplin</option></select></div><div class="field" style="margin-top:12px"><label for="poin">Pengurangan</label><select id="poin" name="poin_pengurangan" class="select"><option value="10">10 poin</option><option value="15">15 poin</option><option value="20">20 poin</option><option value="30">30 poin</option></select></div><div class="field" style="margin-top:12px"><label for="deskripsi">Keterangan</label><textarea id="deskripsi" name="deskripsi" class="textarea"></textarea></div><div class="field" style="margin-top:12px"><label for="bukti">Bukti</label><input id="bukti" name="bukti" type="file" accept=".pdf,.jpg,.jpeg,.png" class="input"></div><button class="button button-primary button-full" style="margin-top:14px">Ajukan</button></form>
        <div class="section-stack"><form method="GET" class="panel panel-pad"><div class="form-grid"><div class="field"><label>Status</label><select name="status" class="select"><option value="semua">Semua</option>@foreach(\App\Models\PenguranganPoinSiswa::DAFTAR_STATUS as $kode=>$label)<option value="{{ $kode }}" @selected($status===$kode)>{{ $label }}</option>@endforeach</select></div><div class="field"><label>Tahun</label><select name="tahun_pelajaran_id" class="select">@foreach($daftarTahunPelajaran as $tahun)<option value="{{ $tahun->id }}" @selected((string)$tahunPelajaranId===(string)$tahun->id)>{{ $tahun->nama }}</option>@endforeach</select></div></div><div class="actions" style="justify-content:flex-end;margin-top:10px"><button class="button button-dark">Terapkan</button></div></form>
            <section class="panel"><div class="mobile-list">@forelse($pengurangan as $item)<article class="mobile-card"><div class="mobile-card-head"><div><p class="person-name">{{ $item->siswa?->nama_lengkap }}</p><p class="person-meta">{{ $item->tanggal_kegiatan?->format('d/m/Y') }} · {{ $item->jenis_kegiatan }}</p></div><span class="badge {{ $item->status==='disetujui'?'badge-active':($item->status==='ditolak'?'badge-inactive':'badge-warning') }}">-{{ $item->poin_pengurangan }}</span></div><p>{{ $item->deskripsi }}</p><p class="person-meta">Status: {{ \App\Models\PenguranganPoinSiswa::DAFTAR_STATUS[$item->status] }}</p>@if($item->bukti)<a href="{{ asset('storage/'.$item->bukti) }}" target="_blank" class="button button-muted button-sm">Lihat bukti</a>@endif @if($item->status==='diajukan' && (auth()->user()?->administrator() || auth()->user()?->memilikiIzin('poin_siswa.putus_konflik')))<form method="POST" action="{{ route('pengurangan-poin-siswa.putuskan',$item) }}" style="margin-top:12px">@csrf @method('PATCH')<textarea name="catatan_keputusan" class="textarea" placeholder="Catatan keputusan"></textarea><div class="actions" style="margin-top:8px"><button name="keputusan" value="ditolak" class="button button-danger button-sm">Tolak</button><button name="keputusan" value="disetujui" class="button button-primary button-sm">Setujui</button></div></form>@endif</article>@empty<div class="empty-state">Belum ada pengajuan pengurangan poin.</div>@endforelse</div></section>
        </div>
    </div>
@endsection
