@extends('layouts.app')
@section('title', 'Kemitraan & MoU - NUSA')
@section('content')
@include('kemitraan-humas._style')
<div class="mitra-page">
    <div class="page-header"><div><p class="eyebrow">Humas</p><h1 class="page-title">Kemitraan & MoU</h1></div>@izin('kemitraan_humas.kelola')<a class="button button-primary" href="{{ route('kemitraan-humas.create') }}">Tambah mitra</a>@endizin</div>
    @include('agenda-humas._messages')
    <p class="agenda-muted">Seluruh kemitraan sekolah</p>
    <div class="agenda-metrics"><div class="agenda-metric"><span>Mitra aktif</span><strong>{{ $statistik['mitra_aktif'] }}</strong></div><div class="agenda-metric"><span>MoU berlaku</span><strong>{{ $statistik['berlaku'] }}</strong></div><div class="agenda-metric agenda-metric--warning"><span>Segera berakhir</span><strong>{{ $statistik['segera_berakhir'] }}</strong></div><div class="agenda-metric"><span>Kedaluwarsa</span><strong style="color:#983d35">{{ $statistik['kedaluwarsa'] }}</strong></div></div>
    <nav class="agenda-tabs" aria-label="Tampilan kemitraan"><a href="{{ route('kemitraan-humas.index') }}" @if ($tab === 'mitra') aria-current="page" @endif>Data mitra</a><a href="{{ route('kemitraan-humas.index', ['tab' => 'mou']) }}" @if ($tab === 'mou') aria-current="page" @endif>Rekap MoU</a></nav>
    <form method="GET" action="{{ route('kemitraan-humas.index') }}"><input type="hidden" name="tab" value="{{ $tab }}">
        <div class="mitra-filters"><div class="field"><label for="kata_kunci">{{ $tab === 'mou' ? 'Cari mitra / judul / nomor MoU' : 'Cari mitra / kontak' }}</label><input class="input" id="kata_kunci" name="kata_kunci" value="{{ $filter['kata_kunci'] ?? '' }}" maxlength="120"></div><div class="field"><label for="jenis">Jenis mitra</label><select id="jenis" name="jenis" class="select"><option value="">Semua jenis</option>@foreach (\App\Models\MitraHumas::JENIS as $kode => $nama)<option value="{{ $kode }}" @selected(($filter['jenis'] ?? '') === $kode)>{{ $nama }}</option>@endforeach</select></div><div class="field"><label for="status_mitra">Status mitra</label><select id="status_mitra" name="status_mitra" class="select"><option value="">Semua status</option>@foreach (\App\Models\MitraHumas::STATUS as $kode => $nama)<option value="{{ $kode }}" @selected(($filter['status_mitra'] ?? '') === $kode)>{{ $nama }}</option>@endforeach</select></div></div>
        @if ($tab === 'mou')<div class="mitra-report-filters"><div class="field"><label for="bidang">Bidang kerja sama</label><select id="bidang" name="bidang" class="select"><option value="">Semua bidang</option>@foreach (\App\Models\KerjaSamaHumas::BIDANG as $kode => $nama)<option value="{{ $kode }}" @selected(($filter['bidang'] ?? '') === $kode)>{{ $nama }}</option>@endforeach</select></div><div class="field"><label for="masa_berlaku">Status MoU</label><select id="masa_berlaku" name="masa_berlaku" class="select"><option value="">Semua status</option>@foreach (\App\Models\KerjaSamaHumas::STATUS_BERLAKU as $kode => $nama)<option value="{{ $kode }}" @selected(($filter['masa_berlaku'] ?? '') === $kode)>{{ $nama }}</option>@endforeach</select></div><div class="field"><label for="dari">Berakhir mulai tanggal</label><input id="dari" name="dari" type="date" class="input" value="{{ $filter['dari'] ?? '' }}"></div><div class="field"><label for="sampai">Berakhir sampai tanggal</label><input id="sampai" name="sampai" type="date" class="input" value="{{ $filter['sampai'] ?? '' }}"></div></div>@endif
        <div class="agenda-actions" style="margin:0 0 22px"><button type="submit" class="button button-primary">Tampilkan</button><a class="button button-muted" href="{{ route('kemitraan-humas.index', ['tab' => $tab]) }}">Reset</a>@if ($tab === 'mou')<a class="button button-muted" href="{{ route('kemitraan-humas.export', $filter) }}">Ekspor Excel</a><a class="button button-muted" href="{{ route('kemitraan-humas.cetak', $filter) }}" target="_blank" rel="noopener">Cetak rekap MoU</a>@endif</div>
    </form>
    @if ($tab === 'mitra')
        @if ($daftarMitra->isEmpty())<div class="agenda-empty">Belum ada mitra yang sesuai.</div>@else<table class="agenda-table agenda-table--list mitra-table mitra-table--mitra"><thead><tr><th>Mitra</th><th>Kontak</th><th>Status</th><th>MoU / agenda</th><th></th></tr></thead><tbody>@foreach ($daftarMitra as $mitra)<tr><td><a href="{{ route('kemitraan-humas.show', $mitra) }}">{{ $mitra->nama }}</a><small>{{ \App\Models\MitraHumas::JENIS[$mitra->jenis] }}</small></td><td data-label="Kontak">{{ $mitra->nama_kontak ?: '-' }}<small>{{ $mitra->nomor_kontak ?: '-' }}</small></td><td data-label="Status"><span class="mitra-badge mitra-badge--{{ $mitra->status }}">{{ \App\Models\MitraHumas::STATUS[$mitra->status] }}</span></td><td data-label="Riwayat">{{ $mitra->kerja_sama_count }} MoU<small>{{ $mitra->agenda_count }} agenda</small></td><td><a class="button button-muted button-sm" href="{{ route('kemitraan-humas.show', $mitra) }}">Rincian</a></td></tr>@endforeach</tbody></table>@endif
        <div style="margin-top:18px">{{ $daftarMitra->links() }}</div>
    @else
        @include('kemitraan-humas._mou-table', ['mou' => $daftarMou, 'sertakanMitra' => true])<div style="margin-top:18px">{{ $daftarMou->links() }}</div>
    @endif
</div>
@endsection
