@extends('layouts.app')
@section('title', ($mitra->exists ? 'Edit mitra' : 'Tambah mitra').' - NUSA')
@section('content')
@include('kemitraan-humas._style')
<div class="mitra-page mitra-form"><div class="page-header"><div><p class="eyebrow">Kemitraan & MoU</p><h1 class="page-title">{{ $mitra->exists ? 'Edit mitra' : 'Tambah mitra' }}</h1></div><a class="button button-muted" href="{{ $mitra->exists ? route('kemitraan-humas.show', $mitra) : route('kemitraan-humas.index') }}">Kembali</a></div>
    @include('agenda-humas._messages')
    <form method="POST" action="{{ $mitra->exists ? route('kemitraan-humas.update', $mitra) : route('kemitraan-humas.store') }}" data-kemitraan-submit>@csrf @if ($mitra->exists)@method('PUT')<input type="hidden" name="versi" value="{{ old('versi', $mitra->versi) }}">@endif
        <section class="agenda-section"><h2>Identitas mitra</h2><div class="agenda-field-grid">
            <div class="field"><label for="nama">Nama instansi / mitra</label><input id="nama" name="nama" class="input" value="{{ old('nama', $mitra->nama) }}" maxlength="180" required></div><div class="field"><label for="jenis">Jenis mitra</label><select id="jenis" name="jenis" class="select" required>@foreach (\App\Models\MitraHumas::JENIS as $kode => $nama)<option value="{{ $kode }}" @selected(old('jenis', $mitra->jenis) === $kode)>{{ $nama }}</option>@endforeach</select></div>
            <div class="field span-2"><label for="alamat">Alamat</label><textarea id="alamat" name="alamat" class="textarea" maxlength="1000" rows="2">{{ old('alamat', $mitra->alamat) }}</textarea></div><div class="field"><label for="website">Website</label><input id="website" name="website" type="url" class="input" value="{{ old('website', $mitra->website) }}" maxlength="1000" placeholder="https://..."></div><div class="field"><label for="status">Status mitra</label><select id="status" name="status" class="select">@foreach (\App\Models\MitraHumas::STATUS as $kode => $nama)<option value="{{ $kode }}" @selected(old('status', $mitra->status) === $kode)>{{ $nama }}</option>@endforeach</select></div>
        </div></section>
        <section class="agenda-section"><h2>Kontak penanggung jawab mitra</h2><div class="agenda-field-grid"><div class="field"><label for="nama_kontak">Nama kontak</label><input id="nama_kontak" name="nama_kontak" class="input" maxlength="180" value="{{ old('nama_kontak', $mitra->nama_kontak) }}"></div><div class="field"><label for="jabatan_kontak">Jabatan</label><input id="jabatan_kontak" name="jabatan_kontak" class="input" maxlength="120" value="{{ old('jabatan_kontak', $mitra->jabatan_kontak) }}"></div><div class="field"><label for="nomor_kontak">Nomor telepon / WhatsApp</label><input id="nomor_kontak" name="nomor_kontak" type="tel" class="input" maxlength="32" value="{{ old('nomor_kontak', $mitra->nomor_kontak) }}"></div><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" class="input" maxlength="180" value="{{ old('email', $mitra->email) }}"></div><div class="field span-2"><label for="catatan">Catatan</label><textarea id="catatan" name="catatan" class="textarea" maxlength="5000" rows="3">{{ old('catatan', $mitra->catatan) }}</textarea></div></div></section>
        <div class="agenda-actions"><button type="submit" class="button button-primary">Simpan mitra</button><a class="button button-muted" href="{{ $mitra->exists ? route('kemitraan-humas.show', $mitra) : route('kemitraan-humas.index') }}">Batal</a>@if ($errors->has('versi'))<a class="button button-muted" href="{{ route('kemitraan-humas.edit', $mitra) }}">Muat ulang data terbaru</a>@endif</div>
    </form>
</div>@include('kemitraan-humas._scripts')
@endsection
