@extends('layouts.app')
@section('title', ($mou->exists ? 'Edit MoU' : 'Tambah MoU').' - NUSA')
@section('content')
@include('kemitraan-humas._style')
<div class="mitra-page mitra-form"><div class="page-header"><div><p class="eyebrow">{{ $mitra->nama }}</p><h1 class="page-title">{{ $mou->exists ? 'Edit MoU' : 'Tambah MoU' }}</h1></div><a class="button button-muted" href="{{ $mou->exists ? route('kemitraan-humas.mou.show', [$mitra, $mou]) : route('kemitraan-humas.show', $mitra) }}">Kembali</a></div>
    @include('agenda-humas._messages')
    <form method="POST" action="{{ $mou->exists ? route('kemitraan-humas.mou.update', [$mitra, $mou]) : route('kemitraan-humas.mou.store', $mitra) }}" data-kemitraan-submit>@csrf @if ($mou->exists)@method('PUT')<input type="hidden" name="versi" value="{{ old('versi', $mou->versi) }}">@endif
        <section class="agenda-section"><h2>Perjanjian kerja sama</h2><div class="agenda-field-grid"><div class="field span-2"><label for="judul">Judul MoU / perjanjian</label><input class="input" id="judul" name="judul" maxlength="180" value="{{ old('judul', $mou->judul) }}" required></div><div class="field"><label for="nomor">Nomor perjanjian</label><input class="input" id="nomor" name="nomor" maxlength="120" value="{{ old('nomor', $mou->nomor) }}"></div><div class="field"><label for="bidang">Bidang kerja sama</label><select id="bidang" name="bidang" class="select" required>@foreach (\App\Models\KerjaSamaHumas::BIDANG as $kode => $nama)<option value="{{ $kode }}" @selected(old('bidang', $mou->bidang) === $kode)>{{ $nama }}</option>@endforeach</select></div><div class="field span-2"><label for="ruang_lingkup">Ruang lingkup / tujuan</label><textarea class="textarea" id="ruang_lingkup" name="ruang_lingkup" maxlength="5000" rows="4" required>{{ old('ruang_lingkup', $mou->ruang_lingkup) }}</textarea></div><div class="field span-2"><label for="penanggung_jawab">Penanggung jawab sekolah</label><input class="input" id="penanggung_jawab" name="penanggung_jawab" maxlength="180" value="{{ old('penanggung_jawab', $mou->penanggung_jawab) }}"></div></div></section>
        <section class="agenda-section"><h2>Masa berlaku & status</h2><div class="agenda-field-grid"><div class="field"><label for="tanggal_mulai">Tanggal mulai</label><input id="tanggal_mulai" name="tanggal_mulai" type="date" class="input" value="{{ old('tanggal_mulai', $mou->tanggal_mulai?->format('Y-m-d')) }}"></div><div class="field"><label for="tanggal_selesai">Tanggal berakhir</label><input id="tanggal_selesai" name="tanggal_selesai" type="date" class="input" value="{{ old('tanggal_selesai', $mou->tanggal_selesai?->format('Y-m-d')) }}"></div><div class="field"><label for="ingatkan_hari_sebelum">Pengingat masa berlaku</label><select id="ingatkan_hari_sebelum" name="ingatkan_hari_sebelum" class="select" required>@foreach (\App\Models\KerjaSamaHumas::PENGINGAT as $hari)<option value="{{ $hari }}" @selected((int) old('ingatkan_hari_sebelum', $mou->ingatkan_hari_sebelum) === $hari)>{{ $hari === 0 ? 'Pada hari berakhir' : $hari.' hari sebelum berakhir' }}</option>@endforeach</select></div><div class="field"><label for="status">Status administrasi</label><select id="status" name="status" class="select" data-mou-status required>@foreach (\App\Models\KerjaSamaHumas::STATUS as $kode => $nama)<option value="{{ $kode }}" @selected(old('status', $mou->status) === $kode)>{{ $nama }}</option>@endforeach</select></div><div class="field span-2" data-alasan-diakhiri @if (old('status', $mou->status) !== 'diakhiri') hidden @endif><label for="alasan_diakhiri">Alasan pengakhiran MoU</label><textarea class="textarea" id="alasan_diakhiri" name="alasan_diakhiri" maxlength="1000" minlength="5" rows="2">{{ old('alasan_diakhiri', $mou->alasan_diakhiri) }}</textarea></div></div></section>
        <section class="agenda-section"><h2>Berkas MoU</h2>@if ($bolehDokumen)<div class="field"><label for="dokumen_humas_id">Dokumen yang sudah tersimpan</label><select id="dokumen_humas_id" name="dokumen_humas_id" class="select"><option value="">Belum ada berkas / tetap draf</option>@foreach ($dokumen as $file)<option value="{{ $file->id }}" @selected(old('dokumen_humas_id', $mou->dokumen_humas_id) == $file->id)>{{ $file->judul }}{{ $file->nomor_dokumen ? ' - '.$file->nomor_dokumen : '' }}{{ $file->status === 'arsip' ? ' (diarsipkan)' : '' }}</option>@endforeach</select></div>@else<p class="agenda-muted">Akses Pusat Dokumen Humas belum diberikan.</p>@endif</section>
        <div class="agenda-actions"><button type="submit" class="button button-primary">Simpan MoU</button><a class="button button-muted" href="{{ $mou->exists ? route('kemitraan-humas.mou.show', [$mitra, $mou]) : route('kemitraan-humas.show', $mitra) }}">Batal</a>@if ($errors->has('versi'))<a class="button button-muted" href="{{ route('kemitraan-humas.mou.edit', [$mitra, $mou]) }}">Muat ulang data terbaru</a>@endif</div>
    </form>
    @if ($bolehDokumen)<form method="GET" action="{{ url()->current() }}" style="margin-top:28px"><div class="agenda-actions"><div class="field" style="flex:1"><label for="cari_dokumen">Cari judul / nomor dokumen lain</label><input class="input" id="cari_dokumen" name="cari_dokumen" maxlength="120" value="{{ request('cari_dokumen') }}"></div><button class="button button-muted" type="submit">Cari dokumen</button></div></form>@endif
</div>@include('kemitraan-humas._scripts')
@endsection
