@extends('layouts.app')
@section('title', 'Aspirasi & Pengaduan - NUSA')
@section('content')
@include('pengaduan-humas._style')
<div class="publikasi-page pengaduan-page">
    <div class="page-header"><div><p class="eyebrow">Humas / Layanan Internal</p><h1 class="page-title">Aspirasi & Pengaduan</h1></div>@izin('pengaduan_humas.kelola')<a class="button button-primary" href="{{ route('pengaduan-humas.create') }}">Catat tiket</a>@endizin</div>
    @include('agenda-humas._messages')
    <div class="agenda-metrics">@foreach (['aktif' => 'Tiket aktif', 'verifikasi' => 'Menunggu verifikasi', 'terlambat' => 'Lewat batas waktu', 'selesai' => 'Selesai'] as $key => $label)<div class="agenda-metric @if($key === 'terlambat') agenda-metric--warning @endif"><span>{{ $label }}</span><strong>{{ $statistik[$key] }}</strong></div>@endforeach</div>
    <section class="agenda-section"><form method="GET" class="pengaduan-filter">
        <div class="field span-2"><label for="kata_kunci">Cari judul atau nomor tiket</label><input class="input" id="kata_kunci" name="kata_kunci" maxlength="120" value="{{ $filter['kata_kunci'] ?? '' }}" placeholder="Judul atau HM-2026-000001"></div>
        @foreach (['status' => ['Status', ['aktif' => 'Semua tiket aktif', 'semua' => 'Semua status'] + \App\Models\PengaduanHumas::STATUS], 'jenis' => ['Jenis', ['' => 'Semua jenis'] + \App\Models\PengaduanHumas::JENIS], 'kategori' => ['Kategori', ['' => 'Semua kategori'] + \App\Models\PengaduanHumas::KATEGORI], 'prioritas' => ['Prioritas', ['' => 'Semua prioritas'] + \App\Models\PengaduanHumas::PRIORITAS], 'tugas' => ['Penugasan', ['semua' => 'Semua dalam akses saya', 'saya' => 'Ditugaskan kepada saya']], 'batas' => ['Batas waktu', ['' => 'Semua batas waktu', 'lewat' => 'Sudah lewat']]] as $name => [$label, $options])<div class="field"><label for="{{ $name }}">{{ $label }}</label><select class="select" id="{{ $name }}" name="{{ $name }}">@foreach ($options as $value => $text)<option value="{{ $value }}" @selected(($filter[$name] ?? ($name === 'status' ? 'aktif' : ($name === 'tugas' ? 'semua' : ''))) === $value)>{{ $text }}</option>@endforeach</select></div>@endforeach
        <div class="field"><label for="mulai">Diterima mulai</label><input class="input" id="mulai" name="mulai" type="date" value="{{ $filter['mulai'] ?? '' }}"></div><div class="field"><label for="sampai">Diterima sampai</label><input class="input" id="sampai" name="sampai" type="date" value="{{ $filter['sampai'] ?? '' }}"></div>
        <div class="agenda-actions" style="margin:0"><button class="button button-muted" type="submit">Tampilkan</button><a href="{{ route('pengaduan-humas.index') }}">Reset filter</a></div>
    </form></section>
    <ul class="pengaduan-list">@forelse ($daftar as $tiket)<li class="pengaduan-row"><div><div class="pengaduan-tags"><strong>{{ $tiket->nomor }}</strong><span class="pengaduan-status pengaduan-status--{{ $tiket->status }}">{{ \App\Models\PengaduanHumas::STATUS[$tiket->status] }}</span>@if ($tiket->prioritas === 'tinggi')<span class="pengaduan-priority">Prioritas tinggi</span>@endif</div><h2><a href="{{ route('pengaduan-humas.show', $tiket) }}">{{ $tiket->judul }}</a></h2><p class="agenda-muted">{{ \App\Models\PengaduanHumas::JENIS[$tiket->jenis] }} &middot; {{ \App\Models\PengaduanHumas::KATEGORI[$tiket->kategori] }} &middot; {{ $tiket->tanggal_diterima->format('d-m-Y') }}</p></div><div><p>{{ $tiket->petugas?->nama ?: 'Belum ditugaskan' }}</p><p class="{{ $tiket->terlambat() ? 'agenda-warning' : 'agenda-muted' }}">{{ $tiket->batas_tanggal ? 'Batas: '.$tiket->batas_tanggal->format('d-m-Y') : 'Belum ada batas waktu' }}@if ($tiket->terlambat()) &middot; Terlambat @endif</p></div><div><a class="button button-muted button-sm" href="{{ route('pengaduan-humas.show', $tiket) }}">Buka tiket</a></div></li>@empty<li class="agenda-empty"><strong>Belum ada tiket yang sesuai.</strong></li>@endforelse</ul>{{ $daftar->links() }}
</div>
@endsection
