@extends('layouts.app')
@section('title', 'Tiket '.$tiket->nomor.' - NUSA')
@section('content')
@include('pengaduan-humas._style')
<div class="publikasi-page pengaduan-page">
    <div class="page-header"><div style="min-width:0"><p class="eyebrow">{{ $tiket->nomor }}</p><h1 class="page-title">{{ $tiket->judul }}</h1><div class="pengaduan-tags"><span class="pengaduan-status pengaduan-status--{{ $tiket->status }}">{{ \App\Models\PengaduanHumas::STATUS[$tiket->status] }}</span>@if ($tiket->prioritas === 'tinggi')<span class="pengaduan-priority">Prioritas tinggi</span>@endif @if ($tiket->terlambat())<span class="agenda-warning">Batas penanganan sudah lewat</span>@endif</div></div><div class="actions"><a class="button button-muted" href="{{ route('pengaduan-humas.index') }}">Daftar tiket</a>@if ($manager && $tiket->aktif() && !$tiket->dariOrangTua())<a class="button button-muted" href="{{ route('pengaduan-humas.edit', $tiket) }}">Koreksi data</a>@endif</div></div>
    @include('agenda-humas._messages')
    <section class="agenda-section"><h2>Laporan yang diterima</h2>@include('pengaduan-humas._rincian', ['dataTiket' => $tiket->snapshot()])<h3>Petugas</h3><p>{{ $tiket->petugas?->nama ?: 'Belum ditugaskan' }}</p>@if ($tiket->diselesaikan_pada)<p class="agenda-muted">Diselesaikan / ditutup: {{ $tiket->diselesaikan_pada->format('d-m-Y H:i') }}</p>@endif</section>
    @if ($manager)
        <details class="pengaduan-details" data-identitas-privat><summary>Identitas pelapor &middot; Privat pengelola</summary><dl class="agenda-facts"><div><dt>Nama pelapor</dt><dd>{{ $tiket->anonim ? 'Tanpa identitas' : $tiket->nama_pelapor }}</dd></div><div><dt>Kontak</dt><dd>{{ $tiket->kontak_pelapor ?: '-' }}</dd></div></dl>@if ($tiket->rahasiakan_identitas)<p class="agenda-warning">Pelapor meminta identitas dirahasiakan dari petugas penanganan.</p>@endif</details>
        <details class="pengaduan-details"><summary>Lampiran privat ({{ $tiket->lampiran->count() }})</summary>@forelse ($tiket->lampiran as $file)<div class="pengaduan-attachment"><strong>{{ $file->nama_file_asli }}</strong><a href="{{ route('pengaduan-humas.berkas', [$tiket, $file]) }}" target="_blank" rel="noopener">Buka</a><a href="{{ route('pengaduan-humas.berkas', [$tiket, $file, 'unduh' => 1]) }}">Unduh</a></div>@empty<p class="agenda-muted">Belum ada lampiran.</p>@endforelse
            @if ($tiket->aktif())<form method="POST" enctype="multipart/form-data" action="{{ route('pengaduan-humas.lampiran.store', $tiket) }}" data-publikasi-upload data-upload-noun="lampiran tiket">@csrf<input type="hidden" name="versi" value="{{ $tiket->versi }}">@include('pengaduan-humas._file-field')<div class="field"><label for="catatan_perubahan">Catatan lampiran</label><textarea class="textarea" id="catatan_perubahan" name="catatan_perubahan" minlength="5" maxlength="2000" required rows="2">{{ old('catatan_perubahan') }}</textarea></div>@include('publikasi-humas._upload-state')<div class="agenda-actions"><button class="button button-muted" type="submit">Tambahkan lampiran</button></div></form>@endif
        </details>
    @else<p class="agenda-muted">Identitas pelapor dan lampiran privat dibatasi untuk pengelola Humas.</p>@endif
    @if ($manager && $tiket->aktif())
        <details class="pengaduan-details" @if ($tiket->status === 'baru') open @endif><summary>Disposisi / ganti petugas</summary><form method="POST" action="{{ route('pengaduan-humas.tindakan', [$tiket, 'disposisi']) }}" data-publikasi-submit>@csrf<input type="hidden" name="versi" value="{{ $tiket->versi }}"><div class="agenda-field-grid"><div class="field"><label for="petugas_pengguna_id">Petugas penanganan</label><select class="select" id="petugas_pengguna_id" name="petugas_pengguna_id" required><option value="">Pilih pegawai</option>@foreach ($kandidat as $petugas)<option value="{{ $petugas->id }}" @selected(old('petugas_pengguna_id', $tiket->petugas_pengguna_id) == $petugas->id)>{{ $petugas->nama }}</option>@endforeach</select></div><div class="field"><label for="batas_tanggal">Batas penanganan</label><input class="input" id="batas_tanggal" name="batas_tanggal" type="date" required min="{{ today()->format('Y-m-d') }}" value="{{ old('batas_tanggal', $tiket->batas_tanggal?->format('Y-m-d')) }}"></div><div class="field span-2"><label for="catatan_disposisi">Arahan / alasan pergantian</label><textarea class="textarea" id="catatan_disposisi" name="catatan" required minlength="5" maxlength="3000" rows="3">{{ old('catatan') }}</textarea></div></div><div class="agenda-actions"><button class="button button-primary" type="submit">Simpan disposisi</button></div></form></details>
        @if ($tiket->petugas_pengguna_id)<details class="pengaduan-details"><summary>Tarik penugasan</summary><form method="POST" action="{{ route('pengaduan-humas.tindakan', [$tiket, 'tarik']) }}" data-publikasi-submit>@csrf<input type="hidden" name="versi" value="{{ $tiket->versi }}"><div class="field"><label for="catatan_tarik">Alasan penarikan</label><textarea class="textarea" id="catatan_tarik" name="catatan" required minlength="5" maxlength="3000" rows="2"></textarea></div><div class="agenda-actions"><button class="button button-muted" type="submit">Tarik penugasan</button></div></form></details>@endif
    @endif
    @if ($bolehMenangani && in_array($tiket->status, ['ditugaskan', 'diproses', 'menunggu']))
        <section class="agenda-section"><h2>Tindak lanjut petugas</h2><form method="POST" action="{{ route('pengaduan-humas.tindakan', [$tiket, 'proses']) }}" data-publikasi-submit>@csrf<input type="hidden" name="versi" value="{{ $tiket->versi }}"><div class="field"><label for="catatan_petugas">Catatan tindakan / hasil penanganan</label><textarea class="textarea" id="catatan_petugas" name="catatan" minlength="5" maxlength="3000" required rows="4">{{ old('catatan') }}</textarea></div><div class="agenda-actions"><button class="button button-primary" type="submit">Catat proses</button><button class="button button-muted" type="submit" formaction="{{ route('pengaduan-humas.tindakan', [$tiket, 'menunggu']) }}">Menunggu informasi</button><button class="button button-muted" type="submit" formaction="{{ route('pengaduan-humas.tindakan', [$tiket, 'usulkan-selesai']) }}">Ajukan selesai</button></div></form></section>
    @endif
    @if ($manager)
        @if ($tiket->aktif())<details class="pengaduan-details" @if ($tiket->status === 'verifikasi') open @endif><summary>Verifikasi / penutupan tiket</summary><form method="POST" action="{{ route('pengaduan-humas.tindakan', [$tiket, 'selesaikan']) }}" data-publikasi-submit>@csrf<input type="hidden" name="versi" value="{{ $tiket->versi }}"><div class="field"><label for="catatan_hasil">Hasil akhir / alasan penutupan</label><textarea class="textarea" id="catatan_hasil" name="catatan" required minlength="5" maxlength="3000" rows="4">{{ old('catatan') }}</textarea></div><div class="agenda-actions"><button class="button button-primary" type="submit">Selesaikan tiket</button><button class="button button-muted agenda-danger" type="submit" formaction="{{ route('pengaduan-humas.tindakan', [$tiket, 'tutup']) }}">Tutup dengan alasan</button></div></form></details>@endif
        @if (in_array($tiket->status, ['verifikasi', 'selesai', 'ditutup']))<details class="pengaduan-details"><summary>{{ $tiket->status === 'verifikasi' ? 'Kembalikan untuk ditindaklanjuti' : 'Buka kembali tiket' }}</summary><form method="POST" action="{{ route('pengaduan-humas.tindakan', [$tiket, 'buka-kembali']) }}" data-publikasi-submit>@csrf<input type="hidden" name="versi" value="{{ $tiket->versi }}"><div class="field"><label for="catatan_buka">Alasan dibuka / dikembalikan</label><textarea class="textarea" id="catatan_buka" name="catatan" minlength="5" maxlength="3000" required rows="3"></textarea></div><div class="agenda-actions"><button class="button button-muted" type="submit">{{ $tiket->status === 'verifikasi' ? 'Kembalikan ke penanganan' : 'Buka kembali tiket' }}</button></div></form></details>@endif
    @endif
    @if ($tiket->dariOrangTua())
        <section class="agenda-section"><h2>Komunikasi dengan pelapor</h2>@include('pengaduan-humas._pesan', ['untukOrangTua' => false])
            @if ($manager && $tiket->pelapor_pengguna_id)
                <form method="POST" action="{{ route('pengaduan-humas.balasan', $tiket) }}" data-publikasi-submit>@csrf<input type="hidden" name="versi" value="{{ $tiket->versi }}"><input type="hidden" name="token_pengiriman" value="{{ old('token_pengiriman', $tokenPengiriman) }}"><div class="field"><label for="isi_balasan">Balasan resmi untuk orang tua</label><textarea class="textarea" id="isi_balasan" name="isi_pesan" rows="4" minlength="5" maxlength="3000" required>{{ old('isi_pesan') }}</textarea></div><div class="agenda-actions"><button class="button button-primary" type="submit">Kirim balasan resmi</button></div></form>
            @endif
        </section>
    @endif
    <section class="agenda-section"><h2>Riwayat penanganan</h2><ul class="publikasi-history">@foreach ($riwayat as $item)<li><div class="pengaduan-tags"><strong>{{ $item->aksi }}</strong><span class="pengaduan-status pengaduan-status--{{ $item->status }}">{{ \App\Models\PengaduanHumas::STATUS[$item->status] }}</span></div><p class="agenda-muted">{{ !$manager && $tiket->dariOrangTua() && in_array($item->aksi, ['Laporan orang tua diterima', 'Informasi pelapor ditambahkan']) ? 'Pelapor' : ($item->pengguna?->nama ?: 'Akun tidak tersedia') }} &middot; {{ $item->created_at->format('d-m-Y H:i') }} &middot; Versi {{ $item->versi + 1 }}</p><div class="agenda-text">{{ $item->catatan }}</div><details><summary>Lihat data tiket pada versi ini</summary><div class="publikasi-snapshot"><h3>{{ $item->snapshot['judul'] }}</h3>@include('pengaduan-humas._rincian', ['dataTiket' => $item->snapshot])</div></details></li>@endforeach</ul>{{ $riwayat->links() }}</section>
</div>
@include('publikasi-humas._scripts')
@include('pengaduan-humas._scripts')
@endsection
