<!DOCTYPE html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Rekap Evaluasi Orang Tua</title>@include('program-kerja-humas._cetak-style')<style>.uf-print-summary th:first-child { width:44%; } .uf-print-summary th,.uf-print-summary td { font-size:9pt; } @media print { @page { size:A4 portrait; margin:12mm; } }</style></head><body>
<div class="print-toolbar"><button type="button" onclick="window.print()">Cetak rekap</button><a href="{{ route('umpan-balik-humas.show',$formulir) }}">Kembali</a></div>
<main class="print-page"><header class="print-header"><img src="{{ asset('images/logo-padang-panjang.png') }}" alt="Logo Padang Panjang"><div><strong>SMP NEGERI 2 PADANG PANJANG</strong><h1>REKAP UMPAN BALIK ORANG TUA</h1></div><img src="{{ asset('images/kartu-pelajar/logo-smpn2pp.png') }}" alt="Logo sekolah"></header>
    <h2>{{ $formulir->judul }}</h2><p>{{ $formulir->tahunPelajaran->nama }} &middot; {{ $formulir->labelStatus() }}<br>{{ $formulir->mulai_pada->format('d-m-Y H:i') }} s.d. {{ $formulir->selesai_pada->format('d-m-Y H:i') }} WIB<br>Penanggung jawab: {{ $formulir->penanggung_jawab }}</p>
    <p>Sasaran: {{ $rekap['sasaran'] }} akun &middot; Respons: {{ $rekap['respons'] }} ({{ number_format($rekap['persen'],1,',','.') }}%)</p>
    <h2>Rekap pertanyaan</h2><table class="uf-print-summary"><thead><tr><th>Pertanyaan</th><th>Menilai</th><th>Rata-rata 1-4</th><th>Puas</th><th>Tidak menilai</th></tr></thead><tbody>@foreach($formulir->pertanyaan as $p)@php($r=$rekap['pertanyaan'][$p->id])<tr><td>{{ $p->urutan }}. {{ $p->teks }}</td>@if($p->jenis==='skala')<td>{{ $r['menilai'] }}</td><td>{{ $r['rata']!==null ? number_format($r['rata'],2,',','.') : '-' }}</td><td>{{ $r['puas']!==null ? number_format($r['puas'],1,',','.').'%' : '-' }}</td><td>{{ $r['skala'][0] }}</td>@else<td colspan="4">{{ $r['teks'] }} jawaban tertulis (isi tidak dicetak)</td>@endif</tr>@endforeach</tbody></table>
    <p><small>Puas = nilai 3 atau 4. Rata-rata dan persentase puas tidak memasukkan Tidak menilai maupun jawaban kosong.</small></p>
    <h2>Tindak lanjut</h2><table><thead><tr><th>Tindakan</th><th>PIC / batas waktu</th><th>Status / hasil</th></tr></thead><tbody>@forelse($formulir->tindakLanjut as $t)<tr><td>{{ $t->uraian }}</td><td>{{ $t->penanggung_jawab }}<br>{{ $t->batas_tanggal->format('d-m-Y') }}</td><td>{{ \App\Models\TindakLanjutUmpanBalikHumas::STATUS[$t->status] }}<br>{{ $t->hasil }}</td></tr>@empty<tr><td colspan="3">Belum ada tindak lanjut.</td></tr>@endforelse</tbody></table>
    <p class="print-note">Dicetak {{ now()->format('d-m-Y H:i') }} WIB oleh {{ auth()->user()->nama }}. Rekap tidak mencantumkan nama akun pengisi dan tidak memuat isi jawaban tertulis.</p>
</main></body></html>
