<!DOCTYPE html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Rekap Prestasi Sekolah - NUSA</title>
@include('program-kerja-humas._cetak-style')
<style>@page { size:A4 landscape; margin:12mm; } .print-page { max-width:273mm; } th,td { font-size:9pt; padding:2mm; } table { min-width:245mm; } .print-table { overflow:auto; } @media print { table { min-width:0; } .print-table { overflow:visible; } }</style></head><body>
<div class="print-toolbar"><button type="button" onclick="window.print()">Cetak rekap</button><a href="{{ route('prestasi-sekolah.index', $filter) }}">Kembali</a></div>
<main class="print-page"><header class="print-header"><img src="{{ asset('images/logo-padang-panjang.png') }}" alt="Logo Padang Panjang"><div><strong>SMP NEGERI 2 PADANG PANJANG</strong><h1>REKAP PRESTASI SEKOLAH</h1><p>Dicetak {{ now()->translatedFormat('d F Y H:i') }}</p></div><img src="{{ asset('images/kartu-pelajar/logo-smpn2pp.png') }}" alt="Logo sekolah"></header>
    <p>Tahun: {{ $filter['tahun'] ?? 'Semua' }} &middot; Status: {{ ['aktif' => 'Draf & terverifikasi', 'semua' => 'Semua status', ...\App\Models\PrestasiSekolah::STATUS][$filter['status'] ?? 'aktif'] }}</p>
    @foreach(['kategori' => ['Kategori', \App\Models\PrestasiSekolah::KATEGORI], 'tingkat' => ['Tingkat', \App\Models\PrestasiSekolah::TINGKAT], 'perolehan' => ['Perolehan', \App\Models\PrestasiSekolah::PEROLEHAN], 'penerima' => ['Penerima', \App\Models\PrestasiSekolah::PENERIMA]] as $key => [$label, $options])@if(filled($filter[$key] ?? null))<p>{{ $label }}: {{ $options[$filter[$key]] }}</p>@endif @endforeach
    @if(filled($filter['tahun_pelajaran_id'] ?? null))<p>Tahun pelajaran: {{ \App\Models\TahunPelajaran::find($filter['tahun_pelajaran_id'])?->nama }}</p>@endif
    @if(filled($filter['kata_kunci'] ?? null))<p>Pencarian: {{ $filter['kata_kunci'] }}</p>@endif
    <p>Catatan sesuai filter: <strong>{{ $statistik['total'] }}</strong> &middot; Terverifikasi: <strong>{{ $statistik['terverifikasi'] }}</strong> &middot; Siswa NUSA berprestasi: <strong>{{ $statistik['siswa'] }}</strong></p>
    <div class="print-table"><table><colgroup><col style="width:4%"><col style="width:10%"><col style="width:25%"><col style="width:12%"><col style="width:25%"><col style="width:14%"><col style="width:10%"></colgroup><thead><tr><th>No.</th><th>Tanggal</th><th>Kegiatan / capaian</th><th>Tingkat / kategori</th><th>Penerima / tim</th><th>Pembina</th><th>Status</th></tr></thead><tbody>
        @forelse($daftar as $p)<tr><td>{{ $loop->iteration }}</td><td>{{ $p->tanggal_prestasi->format('d-m-Y') }}</td><td><strong>{{ $p->capaian }}</strong><br>{{ $p->nama_kegiatan }}@if($p->cabang)<br>{{ $p->cabang }}@endif</td><td>{{ \App\Models\PrestasiSekolah::TINGKAT[$p->tingkat] }}<br>{{ \App\Models\PrestasiSekolah::KATEGORI[$p->kategori] }}</td><td>@if($p->penerima === 'sekolah')SMP Negeri 2 Padang Panjang @else @if($p->nama_tim)<strong>{{ $p->nama_tim }}</strong><br>@endif @foreach($p->peserta as $s)<div>{{ $s->nama }}{{ $s->kelas ? ' - '.$s->kelas : '' }}</div>@endforeach @endif</td><td>{{ $p->pembina ?: '-' }}</td><td>{{ \App\Models\PrestasiSekolah::STATUS[$p->status] }}</td></tr>@empty<tr><td colspan="7">Belum ada prestasi yang sesuai filter.</td></tr>@endforelse
    </tbody></table></div><p class="print-note">Draf dan arsip tidak dihitung dalam statistik prestasi terverifikasi. Bukti privat tidak disertakan dalam cetakan.</p>
</main></body></html>
