@extends('layouts.app')
@section('title', ($prestasi->exists ? 'Edit' : 'Tambah').' Prestasi - NUSA')
@section('prestasi-actions')<a class="button button-muted" href="{{ $prestasi->exists ? route('prestasi-sekolah.show', $prestasi) : route('prestasi-sekolah.index') }}">Kembali</a>@endsection
@section('content')
<div class="publikasi-page prestasi-page kliping-page">
    @include('prestasi-sekolah._header', ['judulHalaman' => $prestasi->exists ? 'Edit prestasi' : 'Tambah prestasi'])
    <form method="POST" enctype="multipart/form-data" action="{{ $prestasi->exists ? route('prestasi-sekolah.update', $prestasi) : route('prestasi-sekolah.store') }}" data-prestasi-form data-publikasi-upload data-upload-noun="prestasi" data-bukti-tersimpan="{{ $prestasi->riwayat_dokumen_humas_id ? 1 : 0 }}">
        @csrf
        @if($prestasi->exists)@method('PUT')<input type="hidden" name="versi" value="{{ old('versi', $prestasi->versi) }}">@else<input type="hidden" name="token_pembuatan" value="{{ old('token_pembuatan', $tokenPembuatan) }}">@endif
        <section class="agenda-section"><h2>Kegiatan & capaian</h2><div class="agenda-field-grid">
            @foreach(['nama_kegiatan' => ['Nama kegiatan / lomba', 180, true], 'capaian' => ['Capaian (misalnya Juara 1 Olimpiade Matematika)', 180, true], 'cabang' => ['Cabang / bidang (opsional)', 120, false], 'penyelenggara' => ['Penyelenggara (opsional)', 180, false], 'tempat' => ['Tempat (opsional)', 180, false], 'pembina' => ['Pembina / pendamping (opsional)', 180, false]] as $key => [$label, $max, $required])<div class="field"><label for="{{ $key }}">{{ $label }}</label><input class="input" id="{{ $key }}" name="{{ $key }}" value="{{ old($key, $prestasi->$key) }}" maxlength="{{ $max }}" @required($required)></div>@endforeach
            <div class="field"><label for="tanggal_prestasi">Tanggal prestasi</label><input class="input" type="date" id="tanggal_prestasi" name="tanggal_prestasi" max="{{ today()->format('Y-m-d') }}" value="{{ old('tanggal_prestasi', $prestasi->tanggal_prestasi?->format('Y-m-d')) }}" required></div>
            <div class="field"><label for="tahun_pelajaran_id">Tahun pelajaran (opsional)</label><select class="select" id="tahun_pelajaran_id" name="tahun_pelajaran_id"><option value="">Tidak dikaitkan</option>@foreach($tahunPelajaran as $t)<option value="{{ $t->id }}" @selected((string)old('tahun_pelajaran_id', $prestasi->tahun_pelajaran_id) === (string)$t->id)>{{ $t->nama }}</option>@endforeach</select></div>
            @foreach(['kategori' => ['Kategori', \App\Models\PrestasiSekolah::KATEGORI], 'tingkat' => ['Tingkat prestasi', \App\Models\PrestasiSekolah::TINGKAT], 'perolehan' => ['Perolehan', \App\Models\PrestasiSekolah::PEROLEHAN]] as $key => [$label, $options])<div class="field"><label for="{{ $key }}">{{ $label }}</label><select class="select" id="{{ $key }}" name="{{ $key }}" required><option value="">Pilih {{ strtolower($label) }}</option>@foreach($options as $code => $name)<option value="{{ $code }}" @selected(old($key, $prestasi->$key) === $code)>{{ $name }}</option>@endforeach</select></div>@endforeach
        </div></section>
        <section class="agenda-section"><h2>Penerima prestasi</h2><div class="agenda-field-grid">
            @foreach(['penerima' => ['Jenis penerima', \App\Models\PrestasiSekolah::PENERIMA], 'bentuk' => ['Bentuk prestasi', \App\Models\PrestasiSekolah::BENTUK]] as $key => [$label, $options])<div class="field"><label for="{{ $key }}">{{ $label }}</label><select class="select" id="{{ $key }}" name="{{ $key }}" required>@foreach($options as $code => $name)<option value="{{ $code }}" @selected(old($key, $prestasi->$key) === $code)>{{ $name }}</option>@endforeach</select></div>@endforeach
            <div class="field span-2" data-team><label for="nama_tim">Nama tim</label><input class="input" id="nama_tim" name="nama_tim" maxlength="180" value="{{ old('nama_tim', $prestasi->nama_tim) }}"></div>
        </div><div data-participants><ul class="prestasi-selected" data-selected></ul><div data-participant-inputs></div><p role="status" class="agenda-muted" data-participant-state></p>
            <div class="prestasi-search"><div class="field"><label for="cari_penerima">Cari identitas NUSA</label><input class="input" type="search" id="cari_penerima" maxlength="120" autocomplete="off"></div><button type="button" class="button button-muted" data-search>Cari penerima</button></div><ul class="prestasi-results" data-results></ul><button type="button" class="button button-muted" data-more hidden>Muat berikutnya</button>
            <details class="agenda-line"><summary>Input nama lama secara manual</summary><div class="agenda-field-grid" style="margin-top:16px"><div class="field"><label for="nama_manual">Nama penerima</label><input class="input" id="nama_manual" maxlength="180"></div><div class="field" data-manual-class><label for="kelas_manual">Kelas saat prestasi (opsional)</label><input class="input" id="kelas_manual" maxlength="80"></div></div><button type="button" class="button button-muted" data-add-manual style="margin-top:12px">Tambahkan penerima</button></details>
        </div><p class="agenda-muted" data-school-recipient hidden>SMP Negeri 2 Padang Panjang</p></section>
        <section class="agenda-section"><h2>Bukti prestasi</h2><div class="field"><label for="tautan">Tautan pengumuman publik (opsional jika ada berkas)</label><input class="input" type="url" id="tautan" name="tautan" maxlength="2000" value="{{ old('tautan', $prestasi->tautan) }}" placeholder="https://"></div>
            @php($metode = old('metode', $prestasi->exists ? 'tetap' : 'tanpa'))
            <fieldset class="kliping-source"><legend class="sr-only">Bukti prestasi</legend>
                @if($prestasi->exists)<label><input type="radio" name="metode" value="tetap" @checked($metode === 'tetap')>Tidak mengganti bukti</label>@else<label><input type="radio" name="metode" value="tanpa" @checked($metode === 'tanpa')>Belum ada berkas / tautan saja</label>@endif
                @izin('dokumen_humas.kelola')<label><input type="radio" name="metode" value="unggah" @checked($metode === 'unggah')>Unggah bukti</label>@endizin
                @if($bolehDokumen)<label><input type="radio" name="metode" value="dokumen" @checked($metode === 'dokumen')>Pilih dokumen Humas</label>@endif
                @if($prestasi->exists && $prestasi->riwayat_dokumen_humas_id)<label><input type="radio" name="metode" value="hapus" @checked($metode === 'hapus')>Lepaskan bukti</label>@endif
            </fieldset>
            @if($prestasi->exists)<p class="agenda-muted" data-bukti-lama>{{ $prestasi->riwayat_dokumen_humas_id ? ($bolehDokumen ? $prestasi->berkas?->nama_file_asli : 'Bukti privat') : 'Belum ada berkas bukti.' }}</p>@endif
            @izin('dokumen_humas.kelola')<div class="field" data-kliping-source="unggah" @if($metode !== 'unggah') hidden @endif><label for="berkas">Sertifikat / bukti PDF, JPG, PNG, WebP (maksimal 10 MB)</label><input class="file-input" type="file" id="berkas" name="berkas" accept=".pdf,.jpg,.jpeg,.png,.webp" @disabled($metode !== 'unggah')><div data-kliping-preview style="margin-top:16px"></div></div>@endizin
            @if($bolehDokumen)<div data-kliping-source="dokumen" @if($metode !== 'dokumen') hidden @endif><div class="field"><label for="cari_dokumen">Cari dokumen bukti</label><input class="input" type="search" id="cari_dokumen" maxlength="120" data-dokumen-search="{{ route('prestasi-sekolah.dokumen') }}" @disabled($metode !== 'dokumen')></div><div class="field" style="margin-top:14px"><label for="dokumen_humas_id">Dokumen Humas</label><select class="select" id="dokumen_humas_id" name="dokumen_humas_id" @disabled($metode !== 'dokumen')><option value="">Pilih dokumen</option>@foreach($dokumen as $d)<option value="{{ $d->id }}" @selected(old('dokumen_humas_id') == $d->id)>{{ $d->judul }}</option>@endforeach</select><p class="agenda-muted" role="status" data-dokumen-state></p></div></div>@endif
        </section>
        <section class="agenda-section"><h2>Status & verifikasi</h2><div class="agenda-field-grid"><div class="field"><label for="status">Status prestasi</label><select class="select" id="status" name="status" required>@foreach(\App\Models\PrestasiSekolah::STATUS as $key => $name)<option value="{{ $key }}" @selected(old('status', $prestasi->status) === $key)>{{ $name }}</option>@endforeach</select></div><div class="field"><label for="catatan">Catatan (opsional)</label><textarea class="textarea" id="catatan" name="catatan" rows="3" maxlength="3000">{{ old('catatan', $prestasi->catatan) }}</textarea></div>
            @if($prestasi->exists)<div class="field span-2"><label for="catatan_perubahan">Alasan perubahan</label><textarea class="textarea" id="catatan_perubahan" name="catatan_perubahan" rows="2" minlength="5" maxlength="2000" required>{{ old('catatan_perubahan') }}</textarea></div>@endif
        </div><label class="prestasi-check" data-verification><input type="checkbox" name="konfirmasi_prestasi" value="1" @checked(old('konfirmasi_prestasi', $prestasi->status === 'terverifikasi'))>Capaian dan penerima telah dicocokkan dengan bukti prestasi.</label></section>
        @include('publikasi-humas._upload-state')
        <div class="agenda-actions"><button type="submit" class="button button-primary">Simpan prestasi</button><a class="button button-muted" href="{{ route('prestasi-sekolah.index') }}">Batal</a></div>
    </form>
</div>
@include('publikasi-humas._scripts')
@include('kliping-berita-humas._scripts')
@include('prestasi-sekolah._scripts')
@endsection
